.TH "bin/agent.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bin/agent.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.bin\&.agent\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpysc2\&.bin\&.agent\&.run_thread\fP (agent_classes, players, map_name, visualize)"
.br
.ti -1c
.RI "def \fBpysc2\&.bin\&.agent\&.main\fP (unused_argv)"
.br
.ti -1c
.RI "def \fBpysc2\&.bin\&.agent\&.entry_point\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpysc2\&.bin\&.agent\&.FLAGS\fP = flags\&.FLAGS"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
