.TH "lib/colors.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/colors.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.lib\&.colors\&.Color\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.lib\&.colors\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpysc2\&.lib\&.colors\&.smooth_hue_palette\fP (scale)"
.br
.ti -1c
.RI "def \fBpysc2\&.lib\&.colors\&.shuffled_hue\fP (scale)"
.br
.ti -1c
.RI "def \fBpysc2\&.lib\&.colors\&.piece_wise_linear\fP (scale, points)"
.br
.ti -1c
.RI "def \fBpysc2\&.lib\&.colors\&.winter\fP (scale)"
.br
.ti -1c
.RI "def \fBpysc2\&.lib\&.colors\&.hot\fP (scale)"
.br
.ti -1c
.RI "def \fBpysc2\&.lib\&.colors\&.unit_type\fP (scale=None)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.black\fP = Color(0, 0, 0)"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.white\fP = Color(255, 255, 255)"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.red\fP = Color(255, 0, 0)"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.green\fP = Color(0, 255, 0)"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.blue\fP = Color(0, 0, 255)"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.cyan\fP = Color(0, 255, 255)"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.yellow\fP = Color(255, 255, 0)"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.purple\fP = Color(255, 0, 255)"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.PLAYER_RELATIVE_PALETTE\fP"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.PLAYER_ABSOLUTE_PALETTE\fP"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.VISIBILITY_PALETTE\fP"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.CAMERA_PALETTE\fP = numpy\&.array([black, white * 0\&.6])"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.CREEP_PALETTE\fP = numpy\&.array([black, purple * 0\&.4])"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.POWER_PALETTE\fP = numpy\&.array([black, cyan * 0\&.7])"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.SELECTED_PALETTE\fP = numpy\&.array([black, green * 0\&.7])"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.effects\fP"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.colors\&.distinct_colors\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
