.TH "env/environment.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
env/environment.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.env\&.environment\&.TimeStep\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.env\&.environment\&.StepType\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.env\&.environment\&.Base\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.env\&.environment\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpysc2\&.env\&.environment\&.reset\fP (self)"
.br
.ti -1c
.RI "def \fBpysc2\&.env\&.environment\&.step\fP (self, action)"
.br
.ti -1c
.RI "def \fBpysc2\&.env\&.environment\&.observation_spec\fP (self)"
.br
.ti -1c
.RI "def \fBpysc2\&.env\&.environment\&.action_spec\fP (self)"
.br
.ti -1c
.RI "def \fBpysc2\&.env\&.environment\&.close\fP (self)"
.br
.ti -1c
.RI "def \fBpysc2\&.env\&.environment\&.__enter__\fP (self)"
.br
.ti -1c
.RI "def \fBpysc2\&.env\&.environment\&.__exit__\fP (self, unused_exception_type, unused_exc_value, unused_traceback)"
.br
.ti -1c
.RI "def \fBpysc2\&.env\&.environment\&.__del__\fP (self)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
