.TH "lib/features.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/features.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.FeatureType\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.PlayerRelative\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.Visibility\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.Effects\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.ScoreCumulative\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.Player\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.UnitLayer\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.FeatureUnit\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.Feature\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.ScreenFeatures\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.MinimapFeatures\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.Dimensions\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.AgentInterfaceFormat\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.features\&.Features\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.lib\&.features\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpysc2\&.lib\&.features\&.parse_agent_interface_format\fP (feature_screen=None, feature_minimap=None, rgb_screen=None, rgb_minimap=None, action_space=None, camera_width_world_units=None, use_feature_units=False)"
.br
.ti -1c
.RI "def \fBpysc2\&.lib\&.features\&.features_from_game_info\fP (game_info, use_feature_units=False, action_space=None, hide_specific_actions=True)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpysc2\&.lib\&.features\&.sw\fP = stopwatch\&.sw"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.features\&.SCREEN_FEATURES\fP"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.features\&.MINIMAP_FEATURES\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
