.TH "bin/gen_versions.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bin/gen_versions.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.bin\&.gen_versions\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpysc2\&.bin\&.gen_versions\&.main\fP (argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBpysc2\&.bin\&.gen_versions\&.VERSIONS_FILE\fP = 'https://raw\&.githubusercontent\&.com/Blizzard/s2client\-proto/master/buildinfo/versions\&.json'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
