.TH "bin/gen_actions.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bin/gen_actions.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.bin\&.gen_actions\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpysc2\&.bin\&.gen_actions\&.get_data\fP ()"
.br
.ti -1c
.RI "def \fBpysc2\&.bin\&.gen_actions\&.generate_name\fP (ability)"
.br
.ti -1c
.RI "def \fBpysc2\&.bin\&.gen_actions\&.sort_key\fP (data, ability)"
.br
.ti -1c
.RI "def \fBpysc2\&.bin\&.gen_actions\&.generate_csv\fP (data)"
.br
.ti -1c
.RI "def \fBpysc2\&.bin\&.gen_actions\&.generate_py_abilities\fP (data)"
.br
.ti -1c
.RI "def \fBpysc2\&.bin\&.gen_actions\&.main\fP (unused_argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpysc2\&.bin\&.gen_actions\&.FLAGS\fP = flags\&.FLAGS"
.br
.ti -1c
.RI "dictionary \fBpysc2\&.bin\&.gen_actions\&.used_abilities\fP"
.br
.ti -1c
.RI "dictionary \fBpysc2\&.bin\&.gen_actions\&.frivolous\fP = {6, 7}"
.br
.ti -1c
.RI "dictionary \fBpysc2\&.bin\&.gen_actions\&.cancel_slot\fP = {313, 1039, 305, 307, 309, 1832, 1834, 3672}"
.br
.ti -1c
.RI "dictionary \fBpysc2\&.bin\&.gen_actions\&.unload_unit\fP = {410, 415, 397, 1440, 2373, 1409, 914, 3670}"
.br
.ti -1c
.RI "dictionary \fBpysc2\&.bin\&.gen_actions\&.skip_abilities\fP = cancel_slot | unload_unit | frivolous"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
