.TH "bin/gen_units.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bin/gen_units.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.bin\&.gen_units\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpysc2\&.bin\&.gen_units\&.get_data\fP ()"
.br
.ti -1c
.RI "def \fBpysc2\&.bin\&.gen_units\&.generate_py_units\fP (data)"
.br
.ti -1c
.RI "def \fBpysc2\&.bin\&.gen_units\&.main\fP (unused_argv)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
