.TH "lib/gfile.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gfile.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.lib\&.gfile\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpysc2\&.lib\&.gfile\&.Exists\fP = os\&.path\&.exists"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.gfile\&.IsDirectory\fP = os\&.path\&.isdir"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.gfile\&.ListDir\fP = os\&.listdir"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.gfile\&.MakeDirs\fP = os\&.makedirs"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.gfile\&.Open\fP = open"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
