.TH "env/mock_sc2_env.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
env/mock_sc2_env.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.env\&.mock_sc2_env\&._TestEnvironment\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.env\&.mock_sc2_env\&.SC2TestEnv\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.env\&.mock_sc2_env\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpysc2\&.env\&.mock_sc2_env\&.DUMMY_MAP_SIZE\fP = point\&.Point(256, 256)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
