.TH "lib/named_array.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/named_array.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.lib\&.named_array\&.NamedDict\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.named_array\&.NamedNumpyArray\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.lib\&.named_array\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
