.TH "run_configs/platforms.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
run_configs/platforms.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.run_configs\&.platforms\&.LocalBase\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.run_configs\&.platforms\&.Windows\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.run_configs\&.platforms\&.Cygwin\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.run_configs\&.platforms\&.MacOS\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.run_configs\&.platforms\&.Linux\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.run_configs\&.platforms\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dictionary \fBpysc2\&.run_configs\&.platforms\&.VERSIONS\fP"
.br
.ti -1c
.RI "\fBpysc2\&.run_configs\&.platforms\&.FLAGS\fP = flags\&.FLAGS"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
