.TH "bin/play_vs_agent.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bin/play_vs_agent.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.bin\&.play_vs_agent\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpysc2\&.bin\&.play_vs_agent\&.main\fP (unused_argv)"
.br
.ti -1c
.RI "def \fBpysc2\&.bin\&.play_vs_agent\&.agent\fP ()"
.br
.ti -1c
.RI "def \fBpysc2\&.bin\&.play_vs_agent\&.human\fP ()"
.br
.ti -1c
.RI "def \fBpysc2\&.bin\&.play_vs_agent\&.entry_point\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpysc2\&.bin\&.play_vs_agent\&.FLAGS\fP = flags\&.FLAGS"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
