.TH "lib/protocol.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/protocol.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.lib\&.protocol\&.ConnectionError\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.protocol\&.ProtocolError\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.protocol\&.StarcraftProtocol\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.lib\&.protocol\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpysc2\&.lib\&.protocol\&.catch_websocket_connection_errors\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpysc2\&.lib\&.protocol\&.FLAGS\fP = flags\&.FLAGS"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.protocol\&.sw\fP = stopwatch\&.sw"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.protocol\&.Status\fP = enum\&.Enum('Status', sc_pb\&.Status\&.items())"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
