.TH "pysc2.lib.stopwatch_test" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.stopwatch_test
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStatTest\fP"
.br
.ti -1c
.RI "class \fBStopwatchTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBham_dist\fP (str1, str2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.stopwatch_test\&.ham_dist ( str1,  str2)"

.PP
.nf
Hamming distance. Count the number of differences between str1 and str2.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
