.TH "pysc2.lib.units" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.units
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNeutral\fP"
.br
.ti -1c
.RI "class \fBProtoss\fP"
.br
.ti -1c
.RI "class \fBTerran\fP"
.br
.ti -1c
.RI "class \fBZerg\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
