.TH "pysc2" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBagents\fP"
.br
.ti -1c
.RI " \fBbin\fP"
.br
.ti -1c
.RI " \fBenv\fP"
.br
.ti -1c
.RI " \fBlib\fP"
.br
.ti -1c
.RI " \fBmaps\fP"
.br
.ti -1c
.RI " \fBrun_configs\fP"
.br
.ti -1c
.RI " \fBtests\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBload_tests\fP (loader, standard_tests, unused_pattern)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.load_tests ( loader,  standard_tests,  unused_pattern)"

.PP
.nf
Our tests end in `_test.py`, so need to override the test discovery.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
