.TH "pysc2.lib.features_test.FeaturesTest" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.features_test.FeaturesTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtestFunctionsIdsAreConsistent\fP (self)"
.br
.ti -1c
.RI "def \fBtestAllVersionsOfAnAbilityHaveTheSameGeneral\fP (self)"
.br
.ti -1c
.RI "def \fBtestValidFunctionsAreConsistent\fP (self)"
.br
.ti -1c
.RI "def \fBgen_random_function_call\fP (self, action_spec, func_id)"
.br
.ti -1c
.RI "def \fBtestIdsMatchIndex\fP (self)"
.br
.ti -1c
.RI "def \fBtestReversingUnknownAction\fP (self)"
.br
.ti -1c
.RI "def \fBtestSpecificActionsAreReversible\fP (self)"
.br
.ti -1c
.RI "def \fBtestCanPickleSpecs\fP (self)"
.br
.ti -1c
.RI "def \fBtestCanPickleFunctionCall\fP (self)"
.br
.ti -1c
.RI "def \fBtestCanDeepcopyNumpyFunctionCall\fP (self)"
.br
.ti -1c
.RI "def \fBtestSizeConstructors\fP (self)"
.br
.ti -1c
.RI "def \fBtestFlRgbActionSpec\fP (self)"
.br
.ti -1c
.RI "def \fBtestFlRgbObservationSpec\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.gen_random_function_call ( self,  action_spec,  func_id)"

.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.testAllVersionsOfAnAbilityHaveTheSameGeneral ( self)"

.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.testCanDeepcopyNumpyFunctionCall ( self)"

.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.testCanPickleFunctionCall ( self)"

.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.testCanPickleSpecs ( self)"

.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.testFlRgbActionSpec ( self)"

.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.testFlRgbObservationSpec ( self)"

.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.testFunctionsIdsAreConsistent ( self)"

.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.testIdsMatchIndex ( self)"

.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.testReversingUnknownAction ( self)"

.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.testSizeConstructors ( self)"

.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.testSpecificActionsAreReversible ( self)"

.PP
.nf
Test that the `transform_action` and `reverse_action` are inverses.
.fi
.PP
 
.SS "def pysc2\&.lib\&.features_test\&.FeaturesTest\&.testValidFunctionsAreConsistent ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
