.TH "pysc2.lib.protocol" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.protocol
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnectionError\fP"
.br
.ti -1c
.RI "class \fBProtocolError\fP"
.br
.ti -1c
.RI "class \fBStarcraftProtocol\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcatch_websocket_connection_errors\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFLAGS\fP = flags\&.FLAGS"
.br
.ti -1c
.RI "\fBsw\fP = stopwatch\&.sw"
.br
.ti -1c
.RI "\fBStatus\fP = enum\&.Enum('Status', sc_pb\&.Status\&.items())"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.protocol\&.catch_websocket_connection_errors ()"

.PP
.nf
A context manager that translates websocket errors into ConnectionError.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.lib\&.protocol\&.FLAGS = flags\&.FLAGS"

.SS "pysc2\&.lib\&.protocol\&.Status = enum\&.Enum('Status', sc_pb\&.Status\&.items())"

.SS "pysc2\&.lib\&.protocol\&.sw = stopwatch\&.sw"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
