.TH "pysc2.lib.units.Neutral" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.units.Neutral
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBBattleStationMineralField\fP = 886"
.br
.ti -1c
.RI "int \fBBattleStationMineralField750\fP = 887"
.br
.ti -1c
.RI "int \fBCollapsibleRockTowerDebris\fP = 490"
.br
.ti -1c
.RI "int \fBCollapsibleRockTowerDiagonal\fP = 588"
.br
.ti -1c
.RI "int \fBCollapsibleRockTowerPushUnit\fP = 561"
.br
.ti -1c
.RI "int \fBCollapsibleTerranTowerDebris\fP = 485"
.br
.ti -1c
.RI "int \fBCollapsibleTerranTowerDiagonal\fP = 589"
.br
.ti -1c
.RI "int \fBCollapsibleTerranTowerPushUnit\fP = 562"
.br
.ti -1c
.RI "int \fBCollapsibleTerranTowerPushUnitRampLeft\fP = 559"
.br
.ti -1c
.RI "int \fBCollapsibleTerranTowerPushUnitRampRight\fP = 560"
.br
.ti -1c
.RI "int \fBCollapsibleTerranTowerRampLeft\fP = 590"
.br
.ti -1c
.RI "int \fBCollapsibleTerranTowerRampRight\fP = 591"
.br
.ti -1c
.RI "int \fBDebrisRampLeft\fP = 486"
.br
.ti -1c
.RI "int \fBDebrisRampRight\fP = 487"
.br
.ti -1c
.RI "int \fBDestructibleDebris6x6\fP = 365"
.br
.ti -1c
.RI "int \fBDestructibleDebrisRampDiagonalHugeBLUR\fP = 377"
.br
.ti -1c
.RI "int \fBDestructibleDebrisRampDiagonalHugeULBR\fP = 376"
.br
.ti -1c
.RI "int \fBDestructibleRock6x6\fP = 371"
.br
.ti -1c
.RI "int \fBDestructibleRockEx1DiagonalHugeBLUR\fP = 641"
.br
.ti -1c
.RI "int \fBKarakFemale\fP = 324"
.br
.ti -1c
.RI "int \fBLabMineralField\fP = 665"
.br
.ti -1c
.RI "int \fBLabMineralField750\fP = 666"
.br
.ti -1c
.RI "int \fBMineralField\fP = 341"
.br
.ti -1c
.RI "int \fBMineralField750\fP = 483"
.br
.ti -1c
.RI "int \fBProtossVespeneGeyser\fP = 608"
.br
.ti -1c
.RI "int \fBPurifierMineralField\fP = 884"
.br
.ti -1c
.RI "int \fBPurifierMineralField750\fP = 885"
.br
.ti -1c
.RI "int \fBPurifierRichMineralField\fP = 796"
.br
.ti -1c
.RI "int \fBPurifierRichMineralField750\fP = 797"
.br
.ti -1c
.RI "int \fBPurifierVespeneGeyser\fP = 880"
.br
.ti -1c
.RI "int \fBRichMineralField\fP = 146"
.br
.ti -1c
.RI "int \fBRichMineralField750\fP = 147"
.br
.ti -1c
.RI "int \fBRichVespeneGeyser\fP = 344"
.br
.ti -1c
.RI "int \fBScantipede\fP = 335"
.br
.ti -1c
.RI "int \fBShakurasVespeneGeyser\fP = 881"
.br
.ti -1c
.RI "int \fBSpacePlatformGeyser\fP = 343"
.br
.ti -1c
.RI "int \fBUnbuildableBricksDestructible\fP = 473"
.br
.ti -1c
.RI "int \fBUnbuildablePlatesDestructible\fP = 474"
.br
.ti -1c
.RI "int \fBUtilityBot\fP = 330"
.br
.ti -1c
.RI "int \fBVespeneGeyser\fP = 342"
.br
.ti -1c
.RI "int \fBXelNagaTower\fP = 149"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Neutral units.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.lib\&.units\&.Neutral\&.BattleStationMineralField = 886\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.BattleStationMineralField750 = 887\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.CollapsibleRockTowerDebris = 490\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.CollapsibleRockTowerDiagonal = 588\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.CollapsibleRockTowerPushUnit = 561\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.CollapsibleTerranTowerDebris = 485\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.CollapsibleTerranTowerDiagonal = 589\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.CollapsibleTerranTowerPushUnit = 562\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.CollapsibleTerranTowerPushUnitRampLeft = 559\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.CollapsibleTerranTowerPushUnitRampRight = 560\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.CollapsibleTerranTowerRampLeft = 590\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.CollapsibleTerranTowerRampRight = 591\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.DebrisRampLeft = 486\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.DebrisRampRight = 487\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.DestructibleDebris6x6 = 365\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.DestructibleDebrisRampDiagonalHugeBLUR = 377\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.DestructibleDebrisRampDiagonalHugeULBR = 376\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.DestructibleRock6x6 = 371\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.DestructibleRockEx1DiagonalHugeBLUR = 641\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.KarakFemale = 324\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.LabMineralField = 665\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.LabMineralField750 = 666\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.MineralField = 341\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.MineralField750 = 483\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.ProtossVespeneGeyser = 608\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.PurifierMineralField = 884\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.PurifierMineralField750 = 885\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.PurifierRichMineralField = 796\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.PurifierRichMineralField750 = 797\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.PurifierVespeneGeyser = 880\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.RichMineralField = 146\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.RichMineralField750 = 147\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.RichVespeneGeyser = 344\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.Scantipede = 335\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.ShakurasVespeneGeyser = 881\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.SpacePlatformGeyser = 343\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.UnbuildableBricksDestructible = 473\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.UnbuildablePlatesDestructible = 474\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.UtilityBot = 330\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.VespeneGeyser = 342\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Neutral\&.XelNagaTower = 149\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
