.TH "pysc2.tests.multi_player_test" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.multi_player_test
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestMultiplayer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBprint_stage\fP (stage)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.multi_player_test\&.print_stage ( stage)"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
