.TH "pysc2.tests.replay_obs_test.ReplayObsTest" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.replay_obs_test.ReplayObsTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.tests\&.utils\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_replay_observations_match\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.replay_obs_test\&.ReplayObsTest\&.test_replay_observations_match ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
