.TH "pysc2.lib.features.Effects" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.features.Effects
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBPsiStorm\fP = 1"
.br
.ti -1c
.RI "int \fBGuardianShield\fP = 2"
.br
.ti -1c
.RI "int \fBTemporalFieldGrowing\fP = 3"
.br
.ti -1c
.RI "int \fBTemporalField\fP = 4"
.br
.ti -1c
.RI "int \fBThermalLance\fP = 5"
.br
.ti -1c
.RI "int \fBScannerSweep\fP = 6"
.br
.ti -1c
.RI "int \fBNukeDot\fP = 7"
.br
.ti -1c
.RI "int \fBLiberatorDefenderZoneSetup\fP = 8"
.br
.ti -1c
.RI "int \fBLiberatorDefenderZone\fP = 9"
.br
.ti -1c
.RI "int \fBBlindingCloud\fP = 10"
.br
.ti -1c
.RI "int \fBCorrosiveBile\fP = 11"
.br
.ti -1c
.RI "int \fBLurkerSpines\fP = 12"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Values for the `effects` feature layer.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.lib\&.features\&.Effects\&.BlindingCloud = 10\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Effects\&.CorrosiveBile = 11\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Effects\&.GuardianShield = 2\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Effects\&.LiberatorDefenderZone = 9\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Effects\&.LiberatorDefenderZoneSetup = 8\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Effects\&.LurkerSpines = 12\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Effects\&.NukeDot = 7\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Effects\&.PsiStorm = 1\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Effects\&.ScannerSweep = 6\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Effects\&.TemporalField = 4\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Effects\&.TemporalFieldGrowing = 3\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Effects\&.ThermalLance = 5\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
