.TH "pysc2.bin.play_vs_agent" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.bin.play_vs_agent
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP (unused_argv)"
.br
.ti -1c
.RI "def \fBagent\fP ()"
.br
.ti -1c
.RI "def \fBhuman\fP ()"
.br
.ti -1c
.RI "def \fBentry_point\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFLAGS\fP = flags\&.FLAGS"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.bin\&.play_vs_agent\&.agent ()"

.PP
.nf
Run the agent, connecting to a (remote) host started independently.
.fi
.PP
 
.SS "def pysc2\&.bin\&.play_vs_agent\&.entry_point ()"

.SS "def pysc2\&.bin\&.play_vs_agent\&.human ()"

.PP
.nf
Run a host which expects one player to connect remotely.
.fi
.PP
 
.SS "def pysc2\&.bin\&.play_vs_agent\&.main ( unused_argv)"

.SH "Variable Documentation"
.PP 
.SS "pysc2\&.bin\&.play_vs_agent\&.FLAGS = flags\&.FLAGS"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
