.TH "pysc2.lib.sc_process" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.sc_process
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSC2LaunchError\fP"
.br
.ti -1c
.RI "class \fBStarcraftProcess\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFLAGS\fP = flags\&.FLAGS"
.br
.ti -1c
.RI "\fBsw\fP = stopwatch\&.sw"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.lib\&.sc_process\&.FLAGS = flags\&.FLAGS"

.SS "pysc2\&.lib\&.sc_process\&.sw = stopwatch\&.sw"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
