.TH "pysc2.tests.replay_obs_test.Config" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.replay_obs_test.Config
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmap_name\fP"
.br
.ti -1c
.RI "\fBcamera_width\fP"
.br
.ti -1c
.RI "\fBrandom_seed\fP"
.br
.ti -1c
.RI "\fBinterface\fP"
.br
.ti -1c
.RI "\fBactions\fP"
.br
.ti -1c
.RI "\fBnum_observations\fP"
.br
.ti -1c
.RI "\fBplayer_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Holds the configuration options.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.tests\&.replay_obs_test\&.Config\&.__init__ ( self)"

.SH "Member Data Documentation"
.PP 
.SS "pysc2\&.tests\&.replay_obs_test\&.Config\&.actions"

.SS "pysc2\&.tests\&.replay_obs_test\&.Config\&.camera_width"

.SS "pysc2\&.tests\&.replay_obs_test\&.Config\&.interface"

.SS "pysc2\&.tests\&.replay_obs_test\&.Config\&.map_name"

.SS "pysc2\&.tests\&.replay_obs_test\&.Config\&.num_observations"

.SS "pysc2\&.tests\&.replay_obs_test\&.Config\&.player_id"

.SS "pysc2\&.tests\&.replay_obs_test\&.Config\&.random_seed"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
