.TH "pysc2.tests.replay_obs_test" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.replay_obs_test
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfig\fP"
.br
.ti -1c
.RI "class \fBGameController\fP"
.br
.ti -1c
.RI "class \fBReplayObsTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBidentity_function\fP (name, args)"
.br
.ti -1c
.RI "def \fBany_point\fP (unit_type, obs)"
.br
.ti -1c
.RI "def \fBavg_point\fP (unit_type, obs)"
.br
.ti -1c
.RI "def \fBselect\fP (func, unit_type)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dictionary \fBprintable_unit_types\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.replay_obs_test\&.any_point ( unit_type,  obs)"

.SS "def pysc2\&.tests\&.replay_obs_test\&.avg_point ( unit_type,  obs)"

.SS "def pysc2\&.tests\&.replay_obs_test\&.identity_function ( name,  args)"

.SS "def pysc2\&.tests\&.replay_obs_test\&.select ( func,  unit_type)"

.SH "Variable Documentation"
.PP 
.SS "dictionary pysc2\&.tests\&.replay_obs_test\&.printable_unit_types"
\fBInitial value:\fP
.PP
.nf
1 =  {
2     _EMPTY: '\&.',
3     units\&.Neutral\&.MineralField: 'm',
4     units\&.Neutral\&.MineralField750: 'm',
5     units\&.Neutral\&.SpacePlatformGeyser: 'G',
6     units\&.Neutral\&.VespeneGeyser: 'G',
7     units\&.Terran\&.Barracks: 'B',
8     units\&.Terran\&.CommandCenter: 'C',
9     units\&.Terran\&.SCV: 's',
10     units\&.Terran\&.Marine: 'M',
11     units\&.Terran\&.SupplyDepot: 'D',
12 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
