.TH "pysc2.lib.renderer_human.SurfType" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.renderer_human.SurfType
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBCHROME\fP = 1"
.br
.ti -1c
.RI "int \fBSCREEN\fP = 2"
.br
.ti -1c
.RI "int \fBMINIMAP\fP = 4"
.br
.ti -1c
.RI "int \fBFEATURE\fP = 8"
.br
.ti -1c
.RI "int \fBRGB\fP = 16"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Used to tell what a mouse click refers to.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.lib\&.renderer_human\&.SurfType\&.CHROME = 1\fC [static]\fP"

.SS "int pysc2\&.lib\&.renderer_human\&.SurfType\&.FEATURE = 8\fC [static]\fP"

.SS "int pysc2\&.lib\&.renderer_human\&.SurfType\&.MINIMAP = 4\fC [static]\fP"

.SS "int pysc2\&.lib\&.renderer_human\&.SurfType\&.RGB = 16\fC [static]\fP"

.SS "int pysc2\&.lib\&.renderer_human\&.SurfType\&.SCREEN = 2\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
