.TH "pysc2.lib.transform.PixelToCoord" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.transform.PixelToCoord
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.lib\&.transform\&.Transform\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBfwd_dist\fP (self, dist)"
.br
.ti -1c
.RI "def \fBfwd_pt\fP (self, pt)"
.br
.ti -1c
.RI "def \fBback_dist\fP (self, dist)"
.br
.ti -1c
.RI "def \fBback_pt\fP (self, pt)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Take a point within a pixel and use the tl, or tl to pixel center.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.transform\&.PixelToCoord\&.__str__ ( self)"

.SS "def pysc2\&.lib\&.transform\&.PixelToCoord\&.back_dist ( self,  dist)"

.SS "def pysc2\&.lib\&.transform\&.PixelToCoord\&.back_pt ( self,  pt)"

.SS "def pysc2\&.lib\&.transform\&.PixelToCoord\&.fwd_dist ( self,  dist)"

.SS "def pysc2\&.lib\&.transform\&.PixelToCoord\&.fwd_pt ( self,  pt)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
