.TH "pysc2.agents.scripted_agent" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.agents.scripted_agent
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCollectMineralShards\fP"
.br
.ti -1c
.RI "class \fBCollectMineralShardsFeatureUnits\fP"
.br
.ti -1c
.RI "class \fBDefeatRoaches\fP"
.br
.ti -1c
.RI "class \fBMoveToBeacon\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFUNCTIONS\fP = actions\&.FUNCTIONS"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.agents\&.scripted_agent\&.FUNCTIONS = actions\&.FUNCTIONS"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
