.TH "pysc2.lib.transform" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.transform
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChain\fP"
.br
.ti -1c
.RI "class \fBLinear\fP"
.br
.ti -1c
.RI "class \fBPixelToCoord\fP"
.br
.ti -1c
.RI "class \fBTransform\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
