.TH "pysc2.lib.point_test.PointTest" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.point_test.PointTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtestBuild\fP (self)"
.br
.ti -1c
.RI "def \fBtestAssignTo\fP (self)"
.br
.ti -1c
.RI "def \fBtestDist\fP (self)"
.br
.ti -1c
.RI "def \fBtestDistSq\fP (self)"
.br
.ti -1c
.RI "def \fBtestLen\fP (self)"
.br
.ti -1c
.RI "def \fBtestScale\fP (self)"
.br
.ti -1c
.RI "def \fBtestScaleMaxSize\fP (self)"
.br
.ti -1c
.RI "def \fBtestScaleMinSize\fP (self)"
.br
.ti -1c
.RI "def \fBtestMinDim\fP (self)"
.br
.ti -1c
.RI "def \fBtestMaxDim\fP (self)"
.br
.ti -1c
.RI "def \fBtestTranspose\fP (self)"
.br
.ti -1c
.RI "def \fBtestRound\fP (self)"
.br
.ti -1c
.RI "def \fBtestCeil\fP (self)"
.br
.ti -1c
.RI "def \fBtestFloor\fP (self)"
.br
.ti -1c
.RI "def \fBtestRotate\fP (self)"
.br
.ti -1c
.RI "def \fBtestContainedCircle\fP (self)"
.br
.ti -1c
.RI "def \fBtestBound\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testAssignTo ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testBound ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testBuild ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testCeil ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testContainedCircle ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testDist ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testDistSq ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testFloor ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testLen ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testMaxDim ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testMinDim ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testRotate ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testRound ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testScale ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testScaleMaxSize ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testScaleMinSize ( self)"

.SS "def pysc2\&.lib\&.point_test\&.PointTest\&.testTranspose ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
