.TH "pysc2.bin.run_tests" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.bin.run_tests
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmodule\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.bin\&.run_tests\&.module"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
