.TH "pysc2.tests.dummy_observation.FeatureUnit" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.dummy_observation.FeatureUnit
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBunit_type\fP, \fBalliance\fP, \fBowner\fP, \fBpos\fP, \fBradius\fP, \fBhealth\fP, \fBhealth_max\fP, \fBis_on_screen\fP, \fBshield\fP=0, \fBshield_max\fP=0, \fBenergy\fP=0, \fBenergy_max\fP=0, \fBcargo_space_taken\fP=0, \fBcargo_space_max\fP=0, \fBbuild_progress\fP=1\&.0, \fBfacing\fP=0\&.0, \fBdisplay_type\fP=raw_pb2\&.Visible, \fBcloak\fP=raw_pb2\&.NotCloaked, \fBis_selected\fP=False, \fBis_blip\fP=False, \fBis_powered\fP=True, \fBmineral_contents\fP=0, \fBvespene_contents\fP=0, \fBassigned_harvesters\fP=0, \fBideal_harvesters\fP=0, \fBweapon_cooldown\fP=0\&.0)"
.br
.ti -1c
.RI "def \fBas_dict\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBunit_type\fP"
.br
.ti -1c
.RI "\fBalliance\fP"
.br
.ti -1c
.RI "\fBowner\fP"
.br
.ti -1c
.RI "\fBpos\fP"
.br
.ti -1c
.RI "\fBradius\fP"
.br
.ti -1c
.RI "\fBhealth\fP"
.br
.ti -1c
.RI "\fBhealth_max\fP"
.br
.ti -1c
.RI "\fBis_on_screen\fP"
.br
.ti -1c
.RI "\fBshield\fP"
.br
.ti -1c
.RI "\fBshield_max\fP"
.br
.ti -1c
.RI "\fBenergy\fP"
.br
.ti -1c
.RI "\fBenergy_max\fP"
.br
.ti -1c
.RI "\fBcargo_space_taken\fP"
.br
.ti -1c
.RI "\fBcargo_space_max\fP"
.br
.ti -1c
.RI "\fBbuild_progress\fP"
.br
.ti -1c
.RI "\fBfacing\fP"
.br
.ti -1c
.RI "\fBdisplay_type\fP"
.br
.ti -1c
.RI "\fBcloak\fP"
.br
.ti -1c
.RI "\fBis_selected\fP"
.br
.ti -1c
.RI "\fBis_blip\fP"
.br
.ti -1c
.RI "\fBis_powered\fP"
.br
.ti -1c
.RI "\fBmineral_contents\fP"
.br
.ti -1c
.RI "\fBvespene_contents\fP"
.br
.ti -1c
.RI "\fBassigned_harvesters\fP"
.br
.ti -1c
.RI "\fBideal_harvesters\fP"
.br
.ti -1c
.RI "\fBweapon_cooldown\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class to hold feature unit data for the builder.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.__init__ ( self,  unit_type,  alliance,  owner,  pos,  radius,  health,  health_max,  is_on_screen,  shield = \fC0\fP,  shield_max = \fC0\fP,  energy = \fC0\fP,  energy_max = \fC0\fP,  cargo_space_taken = \fC0\fP,  cargo_space_max = \fC0\fP,  build_progress = \fC1\&.0\fP,  facing = \fC0\&.0\fP,  display_type = \fCraw_pb2\&.Visible\fP,  cloak = \fCraw_pb2\&.NotCloaked\fP,  is_selected = \fCFalse\fP,  is_blip = \fCFalse\fP,  is_powered = \fCTrue\fP,  mineral_contents = \fC0\fP,  vespene_contents = \fC0\fP,  assigned_harvesters = \fC0\fP,  ideal_harvesters = \fC0\fP,  weapon_cooldown = \fC0\&.0\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.as_dict ( self)"

.SH "Member Data Documentation"
.PP 
.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.alliance"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.assigned_harvesters"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.build_progress"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.cargo_space_max"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.cargo_space_taken"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.cloak"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.display_type"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.energy"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.energy_max"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.facing"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.health"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.health_max"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.ideal_harvesters"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.is_blip"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.is_on_screen"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.is_powered"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.is_selected"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.mineral_contents"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.owner"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.pos"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.radius"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.shield"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.shield_max"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.unit_type"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.vespene_contents"

.SS "pysc2\&.tests\&.dummy_observation\&.FeatureUnit\&.weapon_cooldown"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
