.TH "pysc2.run_configs.platforms.LocalBase" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.run_configs.platforms.LocalBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.run_configs\&.lib\&.RunConfig\fP\&.
.PP
Inherited by \fBpysc2\&.run_configs\&.platforms\&.Cygwin\fP, \fBpysc2\&.run_configs\&.platforms\&.Linux\fP, \fBpysc2\&.run_configs\&.platforms\&.MacOS\fP, and \fBpysc2\&.run_configs\&.platforms\&.Windows\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, base_dir, exec_name, \fBcwd\fP=None, \fBenv\fP=None)"
.br
.ti -1c
.RI "def \fBstart\fP (self, version=None, kwargs)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
Base run config for public installs.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.run_configs\&.platforms\&.LocalBase\&.__init__ ( self,  base_dir,  exec_name,  cwd = \fCNone\fP,  env = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.run_configs\&.platforms\&.LocalBase\&.start ( self,  version = \fCNone\fP,  kwargs)"

.PP
.nf
Launch the game.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
