.TH "pysc2.lib.point" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.point
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPoint\fP"
.br
.ti -1c
.RI "class \fBRect\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBorigin\fP = \fBPoint\fP(0, 0)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.lib\&.point\&.origin = \fBPoint\fP(0, 0)"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
