.TH "pysc2.env.mock_sc2_env_test.TestSC2TestEnv" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.env.mock_sc2_env_test.TestSC2TestEnv
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.env\&.mock_sc2_env_test\&._TestMixin\fP, and TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_episode\fP (self)"
.br
.ti -1c
.RI "def \fBtest_episode_length\fP (self)"
.br
.ti -1c
.RI "def \fBtest_screen_minimap_size\fP (self)"
.br
.ti -1c
.RI "def \fBtest_feature_units_are_supported\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.env\&.mock_sc2_env_test\&.TestSC2TestEnv\&.test_episode ( self)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&.TestSC2TestEnv\&.test_episode_length ( self)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&.TestSC2TestEnv\&.test_feature_units_are_supported ( self)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&.TestSC2TestEnv\&.test_screen_minimap_size ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
