.TH "pysc2.lib.units.Terran" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.units.Terran
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBArmory\fP = 29"
.br
.ti -1c
.RI "int \fBAutoTurret\fP = 31"
.br
.ti -1c
.RI "int \fBBanshee\fP = 55"
.br
.ti -1c
.RI "int \fBBarracks\fP = 21"
.br
.ti -1c
.RI "int \fBBarracksFlying\fP = 46"
.br
.ti -1c
.RI "int \fBBarracksReactor\fP = 38"
.br
.ti -1c
.RI "int \fBBarracksTechLab\fP = 37"
.br
.ti -1c
.RI "int \fBBattlecruiser\fP = 57"
.br
.ti -1c
.RI "int \fBBunker\fP = 24"
.br
.ti -1c
.RI "int \fBCommandCenter\fP = 18"
.br
.ti -1c
.RI "int \fBCommandCenterFlying\fP = 36"
.br
.ti -1c
.RI "int \fBCyclone\fP = 692"
.br
.ti -1c
.RI "int \fBEngineeringBay\fP = 22"
.br
.ti -1c
.RI "int \fBFactory\fP = 27"
.br
.ti -1c
.RI "int \fBFactoryFlying\fP = 43"
.br
.ti -1c
.RI "int \fBFactoryReactor\fP = 40"
.br
.ti -1c
.RI "int \fBFactoryTechLab\fP = 39"
.br
.ti -1c
.RI "int \fBFusionCore\fP = 30"
.br
.ti -1c
.RI "int \fBGhost\fP = 50"
.br
.ti -1c
.RI "int \fBGhostAcademy\fP = 26"
.br
.ti -1c
.RI "int \fBHellion\fP = 53"
.br
.ti -1c
.RI "int \fBHellbat\fP = 484"
.br
.ti -1c
.RI "int \fBKD8Charge\fP = 830"
.br
.ti -1c
.RI "int \fBLiberator\fP = 689"
.br
.ti -1c
.RI "int \fBLiberatorAG\fP = 734"
.br
.ti -1c
.RI "int \fBMULE\fP = 268"
.br
.ti -1c
.RI "int \fBMarauder\fP = 51"
.br
.ti -1c
.RI "int \fBMarine\fP = 48"
.br
.ti -1c
.RI "int \fBMedivac\fP = 54"
.br
.ti -1c
.RI "int \fBMissileTurret\fP = 23"
.br
.ti -1c
.RI "int \fBNuke\fP = 58"
.br
.ti -1c
.RI "int \fBOrbitalCommand\fP = 132"
.br
.ti -1c
.RI "int \fBOrbitalCommandFlying\fP = 134"
.br
.ti -1c
.RI "int \fBPlanetaryFortress\fP = 130"
.br
.ti -1c
.RI "int \fBPointDefenseDrone\fP = 11"
.br
.ti -1c
.RI "int \fBRaven\fP = 56"
.br
.ti -1c
.RI "int \fBReactor\fP = 6"
.br
.ti -1c
.RI "int \fBReaper\fP = 49"
.br
.ti -1c
.RI "int \fBRefinery\fP = 20"
.br
.ti -1c
.RI "int \fBRepairDrone\fP = 1913"
.br
.ti -1c
.RI "int \fBSCV\fP = 45"
.br
.ti -1c
.RI "int \fBSensorTower\fP = 25"
.br
.ti -1c
.RI "int \fBSiegeTank\fP = 33"
.br
.ti -1c
.RI "int \fBSiegeTankSieged\fP = 32"
.br
.ti -1c
.RI "int \fBStarport\fP = 28"
.br
.ti -1c
.RI "int \fBStarportFlying\fP = 44"
.br
.ti -1c
.RI "int \fBStarportReactor\fP = 42"
.br
.ti -1c
.RI "int \fBStarportTechLab\fP = 41"
.br
.ti -1c
.RI "int \fBSupplyDepot\fP = 19"
.br
.ti -1c
.RI "int \fBSupplyDepotLowered\fP = 47"
.br
.ti -1c
.RI "int \fBTechLab\fP = 5"
.br
.ti -1c
.RI "int \fBThor\fP = 52"
.br
.ti -1c
.RI "int \fBThorHighImpactMode\fP = 691"
.br
.ti -1c
.RI "int \fBVikingAssault\fP = 34"
.br
.ti -1c
.RI "int \fBVikingFighter\fP = 35"
.br
.ti -1c
.RI "int \fBWidowMine\fP = 498"
.br
.ti -1c
.RI "int \fBWidowMineBurrowed\fP = 500"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Terran units.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.lib\&.units\&.Terran\&.Armory = 29\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.AutoTurret = 31\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Banshee = 55\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Barracks = 21\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.BarracksFlying = 46\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.BarracksReactor = 38\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.BarracksTechLab = 37\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Battlecruiser = 57\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Bunker = 24\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.CommandCenter = 18\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.CommandCenterFlying = 36\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Cyclone = 692\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.EngineeringBay = 22\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Factory = 27\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.FactoryFlying = 43\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.FactoryReactor = 40\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.FactoryTechLab = 39\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.FusionCore = 30\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Ghost = 50\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.GhostAcademy = 26\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Hellbat = 484\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Hellion = 53\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.KD8Charge = 830\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Liberator = 689\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.LiberatorAG = 734\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Marauder = 51\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Marine = 48\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Medivac = 54\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.MissileTurret = 23\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.MULE = 268\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Nuke = 58\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.OrbitalCommand = 132\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.OrbitalCommandFlying = 134\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.PlanetaryFortress = 130\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.PointDefenseDrone = 11\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Raven = 56\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Reactor = 6\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Reaper = 49\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Refinery = 20\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.RepairDrone = 1913\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.SCV = 45\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.SensorTower = 25\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.SiegeTank = 33\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.SiegeTankSieged = 32\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Starport = 28\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.StarportFlying = 44\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.StarportReactor = 42\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.StarportTechLab = 41\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.SupplyDepot = 19\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.SupplyDepotLowered = 47\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.TechLab = 5\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.Thor = 52\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.ThorHighImpactMode = 691\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.VikingAssault = 34\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.VikingFighter = 35\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.WidowMine = 498\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Terran\&.WidowMineBurrowed = 500\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
