.TH "pysc2.maps.melee" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.maps.melee
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMelee\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBmelee_maps\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list pysc2\&.maps\&.melee\&.melee_maps"
\fBInitial value:\fP
.PP
.nf
1 =  [
2     # "Empty128",  # Not really playable, but may be useful in the future\&.
3     "Flat32",
4     "Flat48",
5     "Flat64",
6     "Flat96",
7     "Flat128",
8     "Simple64",
9     "Simple96",
10     "Simple128",
11 ]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
