.TH "pysc2.maps.lib" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.maps.lib
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDuplicateMapException\fP"
.br
.ti -1c
.RI "class \fBMap\fP"
.br
.ti -1c
.RI "class \fBNoMapException\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_maps\fP ()"
.br
.ti -1c
.RI "def \fBget\fP (map_name)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.maps\&.lib\&.get ( map_name)"

.PP
.nf
Get an instance of a map by name. Errors if the map doesn't exist.
.fi
.PP
 
.SS "def pysc2\&.maps\&.lib\&.get_maps ()"

.PP
.nf
Get the full dict of maps {map_name: map_class}.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
