.TH "pysc2.lib.transform.Transform" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.transform.Transform
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBpysc2\&.lib\&.transform\&.Chain\fP, \fBpysc2\&.lib\&.transform\&.Linear\fP, and \fBpysc2\&.lib\&.transform\&.PixelToCoord\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBfwd_dist\fP (self, dist)"
.br
.ti -1c
.RI "def \fBfwd_pt\fP (self, pt)"
.br
.ti -1c
.RI "def \fBback_dist\fP (self, dist)"
.br
.ti -1c
.RI "def \fBback_pt\fP (self, pt)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Base class for coordinate transforms.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.transform\&.Transform\&.back_dist ( self,  dist)"

.SS "def pysc2\&.lib\&.transform\&.Transform\&.back_pt ( self,  pt)"

.SS "def pysc2\&.lib\&.transform\&.Transform\&.fwd_dist ( self,  dist)"

.SS "def pysc2\&.lib\&.transform\&.Transform\&.fwd_pt ( self,  pt)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
