.TH "pysc2.agents.scripted_agent.DefeatRoaches" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.agents.scripted_agent.DefeatRoaches
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.agents\&.base_agent\&.BaseAgent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBstep\fP (self, obs)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
An agent specifically for solving the DefeatRoaches map.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.agents\&.scripted_agent\&.DefeatRoaches\&.step ( self,  obs)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
