.TH "pysc2.maps" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.maps
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBladder\fP"
.br
.ti -1c
.RI " \fBlib\fP"
.br
.ti -1c
.RI " \fBmelee\fP"
.br
.ti -1c
.RI " \fBmini_games\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBget\fP = lib\&.get"
.br
.ti -1c
.RI "\fBget_maps\fP = lib\&.get_maps"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.maps\&.get = lib\&.get"

.SS "pysc2\&.maps\&.get_maps = lib\&.get_maps"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
