.TH "pysc2.lib.point_test.RectTest" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.point_test.RectTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtestInit\fP (self)"
.br
.ti -1c
.RI "def \fBtestInitBad\fP (self)"
.br
.ti -1c
.RI "def \fBtestInitOnePoint\fP (self)"
.br
.ti -1c
.RI "def \fBtestInitTwoPoints\fP (self)"
.br
.ti -1c
.RI "def \fBtestInitTwoPointsReversed\fP (self)"
.br
.ti -1c
.RI "def \fBtestArea\fP (self)"
.br
.ti -1c
.RI "def \fBtestContains\fP (self)"
.br
.ti -1c
.RI "def \fBtestIntersectsCircle\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.point_test\&.RectTest\&.testArea ( self)"

.SS "def pysc2\&.lib\&.point_test\&.RectTest\&.testContains ( self)"

.SS "def pysc2\&.lib\&.point_test\&.RectTest\&.testInit ( self)"

.SS "def pysc2\&.lib\&.point_test\&.RectTest\&.testInitBad ( self)"

.SS "def pysc2\&.lib\&.point_test\&.RectTest\&.testInitOnePoint ( self)"

.SS "def pysc2\&.lib\&.point_test\&.RectTest\&.testInitTwoPoints ( self)"

.SS "def pysc2\&.lib\&.point_test\&.RectTest\&.testInitTwoPointsReversed ( self)"

.SS "def pysc2\&.lib\&.point_test\&.RectTest\&.testIntersectsCircle ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
