.TH "pysc2.run_configs.lib.Version" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.run_configs.lib.Version
.SH SYNOPSIS
.br
.PP
.PP
Inherits namedtuple, game_version, build_version, data_version, and binary\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Represents a single version of the game.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
