.TH "pysc2.lib.point_flag.PointParser" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.point_flag.PointParser
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArgumentParser\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBparse\fP (self, argument)"
.br
.ti -1c
.RI "def \fBflag_type\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Parse a flag into a point.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.point_flag\&.PointParser\&.flag_type ( self)"

.SS "def pysc2\&.lib\&.point_flag\&.PointParser\&.parse ( self,  argument)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
