.TH "pysc2.lib.actions.ValidActions" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.actions.ValidActions
.SH SYNOPSIS
.br
.PP
.PP
Inherits namedtuple, types, and functions\&.
.SH "Detailed Description"
.PP 

.PP
.nf
The set of types and functions that are valid for an agent to use.

Attributes:
  types: A namedtuple of the types that the functions require. Unlike TYPES
      above, this includes the sizes for screen and minimap.
  functions: A namedtuple of all the functions.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
