.TH "pysc2.lib.features.PlayerRelative" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.features.PlayerRelative
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNONE\fP = 0"
.br
.ti -1c
.RI "int \fBSELF\fP = 1"
.br
.ti -1c
.RI "int \fBALLY\fP = 2"
.br
.ti -1c
.RI "int \fBNEUTRAL\fP = 3"
.br
.ti -1c
.RI "int \fBENEMY\fP = 4"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The values for the `player_relative` feature layers.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.lib\&.features\&.PlayerRelative\&.ALLY = 2\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.PlayerRelative\&.ENEMY = 4\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.PlayerRelative\&.NEUTRAL = 3\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.PlayerRelative\&.NONE = 0\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.PlayerRelative\&.SELF = 1\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
