.TH "pysc2.lib.stopwatch" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.stopwatch
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFakeStopWatchContext\fP"
.br
.ti -1c
.RI "class \fBStat\fP"
.br
.ti -1c
.RI "class \fBStopWatch\fP"
.br
.ti -1c
.RI "class \fBStopWatchContext\fP"
.br
.ti -1c
.RI "class \fBTracingStopWatchContext\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfake_context\fP = \fBFakeStopWatchContext\fP()"
.br
.ti -1c
.RI "\fBsw\fP = \fBStopWatch\fP(enabled=False)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.lib\&.stopwatch\&.fake_context = \fBFakeStopWatchContext\fP()"

.SS "pysc2\&.lib\&.stopwatch\&.sw = \fBStopWatch\fP(enabled=False)"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
