.TH "pysc2.tests.dummy_observation_test.DummyObservationTest" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.dummy_observation_test.DummyObservationTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtestFeatureScreenMatchesSpec\fP (self)"
.br
.ti -1c
.RI "def \fBtestFeatureMinimapMatchesSpec\fP (self)"
.br
.ti -1c
.RI "def \fBtestRgbScreenMatchesSpec\fP (self)"
.br
.ti -1c
.RI "def \fBtestRgbMinimapMatchesSpec\fP (self)"
.br
.ti -1c
.RI "def \fBtestNoSingleSelect\fP (self)"
.br
.ti -1c
.RI "def \fBtestWithSingleSelect\fP (self)"
.br
.ti -1c
.RI "def \fBtestNoMultiSelect\fP (self)"
.br
.ti -1c
.RI "def \fBtestWithMultiSelect\fP (self)"
.br
.ti -1c
.RI "def \fBtestFeatureUnitsAreAdded\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.dummy_observation_test\&.DummyObservationTest\&.setUp ( self)"

.SS "def pysc2\&.tests\&.dummy_observation_test\&.DummyObservationTest\&.testFeatureMinimapMatchesSpec ( self)"

.SS "def pysc2\&.tests\&.dummy_observation_test\&.DummyObservationTest\&.testFeatureScreenMatchesSpec ( self)"

.SS "def pysc2\&.tests\&.dummy_observation_test\&.DummyObservationTest\&.testFeatureUnitsAreAdded ( self)"

.SS "def pysc2\&.tests\&.dummy_observation_test\&.DummyObservationTest\&.testNoMultiSelect ( self)"

.SS "def pysc2\&.tests\&.dummy_observation_test\&.DummyObservationTest\&.testNoSingleSelect ( self)"

.SS "def pysc2\&.tests\&.dummy_observation_test\&.DummyObservationTest\&.testRgbMinimapMatchesSpec ( self)"

.SS "def pysc2\&.tests\&.dummy_observation_test\&.DummyObservationTest\&.testRgbScreenMatchesSpec ( self)"

.SS "def pysc2\&.tests\&.dummy_observation_test\&.DummyObservationTest\&.testWithMultiSelect ( self)"

.SS "def pysc2\&.tests\&.dummy_observation_test\&.DummyObservationTest\&.testWithSingleSelect ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
