.TH "pysc2.maps.mini_games" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.maps.mini_games
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMiniGame\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBmini_games\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list pysc2\&.maps\&.mini_games\&.mini_games"
\fBInitial value:\fP
.PP
.nf
1 =  [
2     "BuildMarines",  # 900s
3     "CollectMineralsAndGas",  # 420s
4     "CollectMineralShards",  # 120s
5     "DefeatRoaches",  # 120s
6     "DefeatZerglingsAndBanelings",  # 120s
7     "FindAndDefeatZerglings",  # 180s
8     "MoveToBeacon",  # 120s
9 ]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
