.TH "pysc2.lib.gfile" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.gfile
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBExists\fP = os\&.path\&.exists"
.br
.ti -1c
.RI "\fBIsDirectory\fP = os\&.path\&.isdir"
.br
.ti -1c
.RI "\fBListDir\fP = os\&.listdir"
.br
.ti -1c
.RI "\fBMakeDirs\fP = os\&.makedirs"
.br
.ti -1c
.RI "\fBOpen\fP = open"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.lib\&.gfile\&.Exists = os\&.path\&.exists"

.SS "pysc2\&.lib\&.gfile\&.IsDirectory = os\&.path\&.isdir"

.SS "pysc2\&.lib\&.gfile\&.ListDir = os\&.listdir"

.SS "pysc2\&.lib\&.gfile\&.MakeDirs = os\&.makedirs"

.SS "pysc2\&.lib\&.gfile\&.Open = open"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
