.TH "pysc2.lib.features.Visibility" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.features.Visibility
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBHIDDEN\fP = 0"
.br
.ti -1c
.RI "int \fBSEEN\fP = 1"
.br
.ti -1c
.RI "int \fBVISIBLE\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Values for the `visibility` feature layers.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.lib\&.features\&.Visibility\&.HIDDEN = 0\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Visibility\&.SEEN = 1\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Visibility\&.VISIBLE = 2\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
