.TH "pysc2.maps.ladder" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.maps.ladder
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLadder\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBladder_seasons\fP"
.br
.ti -1c
.RI "list \fBladder_maps\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list pysc2\&.maps\&.ladder\&.ladder_maps"
\fBInitial value:\fP
.PP
.nf
1 =  [
2     ("Abiogenesis",          Ladder2018Season1, "AbiogenesisLE", 2),
3     ("AbyssalReef",          Ladder2017Season4, "AbyssalReefLE", 2),
4     ("AcidPlant",            Ladder2018Season1, "AcidPlantLE", 2),
5     ("Acolyte",              Ladder2017Season3, "AcolyteLE", 2),
6     ("AscensiontoAiur",      Ladder2017Season4, "AscensiontoAiurLE", 2),
7     ("Backwater",            Ladder2018Season1, "BackwaterLE", 2),
8     ("BattleontheBoardwalk", Ladder2017Season4, "BattleontheBoardwalkLE", 2),
9     ("BelShirVestige",       Ladder2017Season1, "BelShirVestigeLE", 2),
10     ("Blackpink",            Ladder2018Season1, "BlackpinkLE", 2),
11     ("BloodBoil",            Ladder2017Season2, "BloodBoilLE", 2),
12     ("CactusValley",         Ladder2017Season1, "CactusValleyLE", 4),
13     ("Catalyst",             Ladder2018Season1, "CatalystLE", 2),
14     ("DefendersLanding",     Ladder2017Season2, "DefendersLandingLE", 2),
15     ("Eastwatch",            Ladder2018Season1, "EastwatchLE", 2),
16     ("Frost",                Ladder2017Season3, "FrostLE", 2),
17     ("Honorgrounds",         Ladder2017Season1, "HonorgroundsLE", 4),
18     ("Interloper",           Ladder2017Season3, "InterloperLE", 2),
19     ("MechDepot",            Ladder2017Season3, "MechDepotLE", 2),
20     ("NewkirkPrecinct",      Ladder2017Season1, "NewkirkPrecinctTE", 2),
21     ("Odyssey",              Ladder2017Season4, "OdysseyLE", 2),
22     ("PaladinoTerminal",     Ladder2017Season1, "PaladinoTerminalLE", 2),
23     ("ProximaStation",       Ladder2017Season2, "ProximaStationLE", 2),
24     ("Sequencer",            Ladder2017Season2, "SequencerLE", 2),
25 
26     # Disabled due to failing on 4\&.1\&.2 on Linux (Websocket Timeout)\&.
27     # ("NeonVioletSquare",     Ladder2018Season1, "NeonVioletSquareLE", 2),
28 ]
.fi
.SS "list pysc2\&.maps\&.ladder\&.ladder_seasons"
\fBInitial value:\fP
.PP
.nf
1 =  [
2     "Ladder2017Season1",
3     "Ladder2017Season2",
4     "Ladder2017Season3",
5     "Ladder2017Season4",
6     "Ladder2018Season1",
7 ]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
