.TH "pysc2.bin.replay_actions.ProcessStats" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.bin.replay_actions.ProcessStats
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBproc_id\fP)"
.br
.ti -1c
.RI "def \fBupdate\fP (self, \fBstage\fP)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBproc_id\fP"
.br
.ti -1c
.RI "\fBtime\fP"
.br
.ti -1c
.RI "\fBstage\fP"
.br
.ti -1c
.RI "\fBreplay\fP"
.br
.ti -1c
.RI "\fBreplay_stats\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Stats for a worker process.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.bin\&.replay_actions\&.ProcessStats\&.__init__ ( self,  proc_id)"

.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.bin\&.replay_actions\&.ProcessStats\&.__str__ ( self)"

.SS "def pysc2\&.bin\&.replay_actions\&.ProcessStats\&.update ( self,  stage)"

.SH "Member Data Documentation"
.PP 
.SS "pysc2\&.bin\&.replay_actions\&.ProcessStats\&.proc_id"

.SS "pysc2\&.bin\&.replay_actions\&.ProcessStats\&.replay"

.SS "pysc2\&.bin\&.replay_actions\&.ProcessStats\&.replay_stats"

.SS "pysc2\&.bin\&.replay_actions\&.ProcessStats\&.stage"

.SS "pysc2\&.bin\&.replay_actions\&.ProcessStats\&.time"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
