.TH "pysc2.env.environment.Base" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.env.environment.Base
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBpysc2\&.env\&.base_env_wrapper\&.BaseEnvWrapper\fP, \fBpysc2\&.env\&.mock_sc2_env\&._TestEnvironment\fP, and \fBpysc2\&.env\&.sc2_env\&.SC2Env\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
