.TH "pysc2.lib.remote_controller.RequestError" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.remote_controller.RequestError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, description, \fBres\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBres\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.lib\&.remote_controller\&.RequestError\&.__init__ ( self,  description,  res)"

.SH "Member Data Documentation"
.PP 
.SS "pysc2\&.lib\&.remote_controller\&.RequestError\&.res"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
