.TH "pysc2.lib.features_test" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.features_test
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAvailableActionsTest\fP"
.br
.ti -1c
.RI "class \fBDimensionsTest\fP"
.br
.ti -1c
.RI "class \fBFeaturesTest\fP"
.br
.ti -1c
.RI "class \fBTestParseAgentInterfaceFormat\fP"
.br
.ti -1c
.RI "class \fBToPointTest\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBobservation_text_proto\fP"
.br
.ti -1c
.RI "\fBRECTANGULAR_DIMENSIONS\fP = \fBfeatures\&.Dimensions\fP(screen=(84, 80), minimap=(64, 67))"
.br
.ti -1c
.RI "\fBSQUARE_DIMENSIONS\fP = \fBfeatures\&.Dimensions\fP(screen=84, minimap=64)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string pysc2\&.lib\&.features_test\&.observation_text_proto"
\fBInitial value:\fP
.PP
.nf
1 =  """
2 player_common {
3   player_id: 1
4   minerals: 0
5   vespene: 0
6   food_cap: 10
7   food_used: 0
8   food_army: 0
9   food_workers: 0
10   idle_worker_count: 0
11   army_count: 0
12   warp_gate_count: 0
13   larva_count: 0
14 }
15 game_loop: 20
16 """
.fi
.SS "pysc2\&.lib\&.features_test\&.RECTANGULAR_DIMENSIONS = \fBfeatures\&.Dimensions\fP(screen=(84, 80), minimap=(64, 67))"

.SS "pysc2\&.lib\&.features_test\&.SQUARE_DIMENSIONS = \fBfeatures\&.Dimensions\fP(screen=84, minimap=64)"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
