.TH "pysc2.env.base_env_wrapper.BaseEnvWrapper" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.env.base_env_wrapper.BaseEnvWrapper
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.env\&.environment\&.Base\fP\&.
.PP
Inherited by \fBpysc2\&.env\&.available_actions_printer\&.AvailableActionsPrinter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, env)"
.br
.ti -1c
.RI "def \fBclose\fP (self, args, kwargs)"
.br
.ti -1c
.RI "def \fBaction_spec\fP (self, args, kwargs)"
.br
.ti -1c
.RI "def \fBobservation_spec\fP (self, args, kwargs)"
.br
.ti -1c
.RI "def \fBreset\fP (self, args, kwargs)"
.br
.ti -1c
.RI "def \fBstep\fP (self, args, kwargs)"
.br
.ti -1c
.RI "def \fBsave_replay\fP (self, args, kwargs)"
.br
.ti -1c
.RI "def \fBstate\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A base env wrapper so we don't need to override everything every time.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.env\&.base_env_wrapper\&.BaseEnvWrapper\&.__init__ ( self,  env)"

.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.env\&.base_env_wrapper\&.BaseEnvWrapper\&.action_spec ( self,  args,  kwargs)"

.SS "def pysc2\&.env\&.base_env_wrapper\&.BaseEnvWrapper\&.close ( self,  args,  kwargs)"

.SS "def pysc2\&.env\&.base_env_wrapper\&.BaseEnvWrapper\&.observation_spec ( self,  args,  kwargs)"

.SS "def pysc2\&.env\&.base_env_wrapper\&.BaseEnvWrapper\&.reset ( self,  args,  kwargs)"

.SS "def pysc2\&.env\&.base_env_wrapper\&.BaseEnvWrapper\&.save_replay ( self,  args,  kwargs)"

.SS "def pysc2\&.env\&.base_env_wrapper\&.BaseEnvWrapper\&.state ( self)"

.SS "def pysc2\&.env\&.base_env_wrapper\&.BaseEnvWrapper\&.step ( self,  args,  kwargs)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
