.TH "pysc2.lib.named_array_test.NamedArrayTest" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.named_array_test.NamedArrayTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBassertArrayEqual\fP (self, a, b)"
.br
.ti -1c
.RI "def \fBtest_bad_names\fP (self, names)"
.br
.ti -1c
.RI "def \fBtest_single_dimension\fP (self, names)"
.br
.ti -1c
.RI "def \fBtest_empty_array\fP (self)"
.br
.ti -1c
.RI "def \fBtest_named_array_multi_first\fP (self)"
.br
.ti -1c
.RI "def \fBtest_named_array_multi_second\fP (self)"
.br
.ti -1c
.RI "def \fBtest_string\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.named_array_test\&.NamedArrayTest\&.assertArrayEqual ( self,  a,  b)"

.SS "def pysc2\&.lib\&.named_array_test\&.NamedArrayTest\&.test_bad_names ( self,  names)"

.SS "def pysc2\&.lib\&.named_array_test\&.NamedArrayTest\&.test_empty_array ( self)"

.SS "def pysc2\&.lib\&.named_array_test\&.NamedArrayTest\&.test_named_array_multi_first ( self)"

.SS "def pysc2\&.lib\&.named_array_test\&.NamedArrayTest\&.test_named_array_multi_second ( self)"

.SS "def pysc2\&.lib\&.named_array_test\&.NamedArrayTest\&.test_single_dimension ( self,  names)"

.SS "def pysc2\&.lib\&.named_array_test\&.NamedArrayTest\&.test_string ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
