.TH "pysc2.lib.transform.Chain" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.transform.Chain
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.lib\&.transform\&.Transform\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, args)"
.br
.ti -1c
.RI "def \fBfwd_dist\fP (self, dist)"
.br
.ti -1c
.RI "def \fBfwd_pt\fP (self, pt)"
.br
.ti -1c
.RI "def \fBback_dist\fP (self, dist)"
.br
.ti -1c
.RI "def \fBback_pt\fP (self, pt)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtransforms\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Chain a set of transforms: Chain(a_to_b, b_to_c) => a_to_c.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.lib\&.transform\&.Chain\&.__init__ ( self,  args)"

.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.transform\&.Chain\&.__str__ ( self)"

.SS "def pysc2\&.lib\&.transform\&.Chain\&.back_dist ( self,  dist)"

.SS "def pysc2\&.lib\&.transform\&.Chain\&.back_pt ( self,  pt)"

.SS "def pysc2\&.lib\&.transform\&.Chain\&.fwd_dist ( self,  dist)"

.SS "def pysc2\&.lib\&.transform\&.Chain\&.fwd_pt ( self,  pt)"

.SH "Member Data Documentation"
.PP 
.SS "pysc2\&.lib\&.transform\&.Chain\&.transforms"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
