.TH "pysc2.lib.features_test.TestParseAgentInterfaceFormat" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.features_test.TestParseAgentInterfaceFormat
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_no_arguments_raises\fP (self)"
.br
.ti -1c
.RI "def \fBtest_invalid_feature_combinations_raise\fP (self, screen, minimap)"
.br
.ti -1c
.RI "def \fBtest_valid_feature_specification_is_parsed\fP (self)"
.br
.ti -1c
.RI "def \fBtest_invalid_minimap_combinations_raise\fP (self, screen, minimap)"
.br
.ti -1c
.RI "def \fBtest_valid_minimap_specification_is_parsed\fP (self)"
.br
.ti -1c
.RI "def \fBtest_invalid_action_space_raises\fP (self)"
.br
.ti -1c
.RI "def \fBtest_valid_action_space_is_parsed\fP (self, action_space)"
.br
.ti -1c
.RI "def \fBtest_camera_width_world_units_are_parsed\fP (self)"
.br
.ti -1c
.RI "def \fBtest_use_feature_units_is_parsed\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.features_test\&.TestParseAgentInterfaceFormat\&.test_camera_width_world_units_are_parsed ( self)"

.SS "def pysc2\&.lib\&.features_test\&.TestParseAgentInterfaceFormat\&.test_invalid_action_space_raises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.TestParseAgentInterfaceFormat\&.test_invalid_feature_combinations_raise ( self,  screen,  minimap)"

.SS "def pysc2\&.lib\&.features_test\&.TestParseAgentInterfaceFormat\&.test_invalid_minimap_combinations_raise ( self,  screen,  minimap)"

.SS "def pysc2\&.lib\&.features_test\&.TestParseAgentInterfaceFormat\&.test_no_arguments_raises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.TestParseAgentInterfaceFormat\&.test_use_feature_units_is_parsed ( self)"

.SS "def pysc2\&.lib\&.features_test\&.TestParseAgentInterfaceFormat\&.test_valid_action_space_is_parsed ( self,  action_space)"

.SS "def pysc2\&.lib\&.features_test\&.TestParseAgentInterfaceFormat\&.test_valid_feature_specification_is_parsed ( self)"

.SS "def pysc2\&.lib\&.features_test\&.TestParseAgentInterfaceFormat\&.test_valid_minimap_specification_is_parsed ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
