.TH "pysc2.bin.replay_actions.ReplayStats" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.bin.replay_actions.ReplayStats
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBmerge\fP (self, other)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBreplays\fP"
.br
.ti -1c
.RI "\fBsteps\fP"
.br
.ti -1c
.RI "\fBcamera_move\fP"
.br
.ti -1c
.RI "\fBselect_pt\fP"
.br
.ti -1c
.RI "\fBselect_rect\fP"
.br
.ti -1c
.RI "\fBcontrol_group\fP"
.br
.ti -1c
.RI "\fBmaps\fP"
.br
.ti -1c
.RI "\fBraces\fP"
.br
.ti -1c
.RI "\fBunit_ids\fP"
.br
.ti -1c
.RI "\fBvalid_abilities\fP"
.br
.ti -1c
.RI "\fBmade_abilities\fP"
.br
.ti -1c
.RI "\fBvalid_actions\fP"
.br
.ti -1c
.RI "\fBmade_actions\fP"
.br
.ti -1c
.RI "\fBcrashing_replays\fP"
.br
.ti -1c
.RI "\fBinvalid_replays\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Summary stats of the replays seen so far.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.bin\&.replay_actions\&.ReplayStats\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.bin\&.replay_actions\&.ReplayStats\&.__str__ ( self)"

.SS "def pysc2\&.bin\&.replay_actions\&.ReplayStats\&.merge ( self,  other)"

.PP
.nf
Merge another ReplayStats into this one.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.camera_move"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.control_group"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.crashing_replays"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.invalid_replays"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.made_abilities"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.made_actions"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.maps"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.races"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.replays"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.select_pt"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.select_rect"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.steps"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.unit_ids"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.valid_abilities"

.SS "pysc2\&.bin\&.replay_actions\&.ReplayStats\&.valid_actions"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
