.TH "pysc2.lib.features.ScoreCumulative" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.features.ScoreCumulative
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBscore\fP = 0"
.br
.ti -1c
.RI "int \fBidle_production_time\fP = 1"
.br
.ti -1c
.RI "int \fBidle_worker_time\fP = 2"
.br
.ti -1c
.RI "int \fBtotal_value_units\fP = 3"
.br
.ti -1c
.RI "int \fBtotal_value_structures\fP = 4"
.br
.ti -1c
.RI "int \fBkilled_value_units\fP = 5"
.br
.ti -1c
.RI "int \fBkilled_value_structures\fP = 6"
.br
.ti -1c
.RI "int \fBcollected_minerals\fP = 7"
.br
.ti -1c
.RI "int \fBcollected_vespene\fP = 8"
.br
.ti -1c
.RI "int \fBcollection_rate_minerals\fP = 9"
.br
.ti -1c
.RI "int \fBcollection_rate_vespene\fP = 10"
.br
.ti -1c
.RI "int \fBspent_minerals\fP = 11"
.br
.ti -1c
.RI "int \fBspent_vespene\fP = 12"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Indices into the `score_cumulative` observation.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.collected_minerals = 7\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.collected_vespene = 8\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.collection_rate_minerals = 9\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.collection_rate_vespene = 10\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.idle_production_time = 1\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.idle_worker_time = 2\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.killed_value_structures = 6\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.killed_value_units = 5\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.score = 0\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.spent_minerals = 11\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.spent_vespene = 12\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.total_value_structures = 4\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.ScoreCumulative\&.total_value_units = 3\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
