.TH "pysc2.lib.point_test.FakePoint" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.point_test.FakePoint
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBx\fP"
.br
.ti -1c
.RI "\fBy\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.lib\&.point_test\&.FakePoint\&.__init__ ( self)"

.SH "Member Data Documentation"
.PP 
.SS "pysc2\&.lib\&.point_test\&.FakePoint\&.x"

.SS "pysc2\&.lib\&.point_test\&.FakePoint\&.y"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
