.TH "pysc2.lib.features.UnitLayer" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.features.UnitLayer
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBunit_type\fP = 0"
.br
.ti -1c
.RI "int \fBplayer_relative\fP = 1"
.br
.ti -1c
.RI "int \fBhealth\fP = 2"
.br
.ti -1c
.RI "int \fBshields\fP = 3"
.br
.ti -1c
.RI "int \fBenergy\fP = 4"
.br
.ti -1c
.RI "int \fBtransport_slots_taken\fP = 5"
.br
.ti -1c
.RI "int \fBbuild_progress\fP = 6"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Indices into the unit layers in the observations.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.lib\&.features\&.UnitLayer\&.build_progress = 6\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.UnitLayer\&.energy = 4\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.UnitLayer\&.health = 2\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.UnitLayer\&.player_relative = 1\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.UnitLayer\&.shields = 3\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.UnitLayer\&.transport_slots_taken = 5\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.UnitLayer\&.unit_type = 0\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
