.TH "pysc2.bin.gen_versions" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.bin.gen_versions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP (argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBVERSIONS_FILE\fP = 'https://raw\&.githubusercontent\&.com/Blizzard/s2client\-proto/master/buildinfo/versions\&.json'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.bin\&.gen_versions\&.main ( argv)"

.SH "Variable Documentation"
.PP 
.SS "string pysc2\&.bin\&.gen_versions\&.VERSIONS_FILE = 'https://raw\&.githubusercontent\&.com/Blizzard/s2client\-proto/master/buildinfo/versions\&.json'"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
