.TH "pysc2.maps.melee.Melee" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.maps.melee.Melee
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.maps\&.lib\&.Map\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBdirectory\fP = 'Melee'"
.br
.ti -1c
.RI "string \fBdownload\fP = 'https://github\&.com/Blizzard/s2client\-proto#map\-packs'"
.br
.ti -1c
.RI "int \fBplayers\fP = 2"
.br
.ti -1c
.RI "int \fBgame_steps_per_episode\fP = 16 * 60 * 30"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Data Documentation"
.PP 
.SS "string pysc2\&.maps\&.melee\&.Melee\&.directory = 'Melee'\fC [static]\fP"

.SS "string pysc2\&.maps\&.melee\&.Melee\&.download = 'https://github\&.com/Blizzard/s2client\-proto#map\-packs'\fC [static]\fP"

.SS "int pysc2\&.maps\&.melee\&.Melee\&.game_steps_per_episode = 16 * 60 * 30\fC [static]\fP"

.SS "int pysc2\&.maps\&.melee\&.Melee\&.players = 2\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
