.TH "pysc2.env.mock_sc2_env_test._TestMixin" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.env.mock_sc2_env_test._TestMixin
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBpysc2\&.env\&.mock_sc2_env_test\&.TestSC2TestEnv\fP, and \fBpysc2\&.env\&.mock_sc2_env_test\&.TestTestEnvironment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBassert_spec\fP (self, array, shape, dtype)"
.br
.ti -1c
.RI "def \fBassert_equal\fP (self, actual, expected)"
.br
.ti -1c
.RI "def \fBassert_reset\fP (self, env)"
.br
.ti -1c
.RI "def \fBassert_first_step\fP (self, env)"
.br
.ti -1c
.RI "def \fBassert_mid_step\fP (self, env)"
.br
.ti -1c
.RI "def \fBassert_last_step\fP (self, env)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.env\&.mock_sc2_env_test\&._TestMixin\&.assert_equal ( self,  actual,  expected)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&._TestMixin\&.assert_first_step ( self,  env)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&._TestMixin\&.assert_last_step ( self,  env)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&._TestMixin\&.assert_mid_step ( self,  env)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&._TestMixin\&.assert_reset ( self,  env)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&._TestMixin\&.assert_spec ( self,  array,  shape,  dtype)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
