.TH "pysc2.lib.named_array.NamedDict" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.named_array.NamedDict
.SH SYNOPSIS
.br
.PP
.PP
Inherits dict\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, args, kwargs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A dict where you can use `d["element"]` or `d.element`.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.lib\&.named_array\&.NamedDict\&.__init__ ( self,  args,  kwargs)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
