.TH "pysc2.lib.features.Player" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.features.Player
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBplayer_id\fP = 0"
.br
.ti -1c
.RI "int \fBminerals\fP = 1"
.br
.ti -1c
.RI "int \fBvespene\fP = 2"
.br
.ti -1c
.RI "int \fBfood_used\fP = 3"
.br
.ti -1c
.RI "int \fBfood_cap\fP = 4"
.br
.ti -1c
.RI "int \fBfood_army\fP = 5"
.br
.ti -1c
.RI "int \fBfood_workers\fP = 6"
.br
.ti -1c
.RI "int \fBidle_worker_count\fP = 7"
.br
.ti -1c
.RI "int \fBarmy_count\fP = 8"
.br
.ti -1c
.RI "int \fBwarp_gate_count\fP = 9"
.br
.ti -1c
.RI "int \fBlarva_count\fP = 10"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Indices into the `player` observation.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.lib\&.features\&.Player\&.army_count = 8\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Player\&.food_army = 5\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Player\&.food_cap = 4\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Player\&.food_used = 3\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Player\&.food_workers = 6\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Player\&.idle_worker_count = 7\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Player\&.larva_count = 10\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Player\&.minerals = 1\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Player\&.player_id = 0\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Player\&.vespene = 2\fC [static]\fP"

.SS "int pysc2\&.lib\&.features\&.Player\&.warp_gate_count = 9\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
