.TH "pysc2.lib.stopwatch.StopWatchContext" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.stopwatch.StopWatchContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBpysc2\&.lib\&.stopwatch\&.TracingStopWatchContext\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, stopwatch, name)"
.br
.ti -1c
.RI "def \fB__enter__\fP (self)"
.br
.ti -1c
.RI "def \fB__exit__\fP (self, unused_exception_type, unused_exc_value, unused_traceback)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Time an individual call.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.lib\&.stopwatch\&.StopWatchContext\&.__init__ ( self,  stopwatch,  name)"

.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.stopwatch\&.StopWatchContext\&.__enter__ ( self)"

.SS "def pysc2\&.lib\&.stopwatch\&.StopWatchContext\&.__exit__ ( self,  unused_exception_type,  unused_exc_value,  unused_traceback)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
