.TH "pysc2.lib.stopwatch.TracingStopWatchContext" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.stopwatch.TracingStopWatchContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.lib\&.stopwatch\&.StopWatchContext\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__enter__\fP (self)"
.br
.ti -1c
.RI "def \fB__exit__\fP (self, args, kwargs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Time an individual call, but also output all the enter/exit calls.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.stopwatch\&.TracingStopWatchContext\&.__enter__ ( self)"

.SS "def pysc2\&.lib\&.stopwatch\&.TracingStopWatchContext\&.__exit__ ( self,  args,  kwargs)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
