.TH "pysc2.run_configs.platforms" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.run_configs.platforms
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCygwin\fP"
.br
.ti -1c
.RI "class \fBLinux\fP"
.br
.ti -1c
.RI "class \fBLocalBase\fP"
.br
.ti -1c
.RI "class \fBMacOS\fP"
.br
.ti -1c
.RI "class \fBWindows\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dictionary \fBVERSIONS\fP"
.br
.ti -1c
.RI "\fBFLAGS\fP = flags\&.FLAGS"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.run_configs\&.platforms\&.FLAGS = flags\&.FLAGS"

.SS "dictionary pysc2\&.run_configs\&.platforms\&.VERSIONS"
\fBInitial value:\fP
.PP
.nf
1 =  {ver\&.game_version: ver for ver in [
2     lib\&.Version("3\&.16\&.1", 55958, "5BD7C31B44525DAB46E64C4602A81DC2", None),
3     lib\&.Version("3\&.17\&.0", 56787, "DFD1F6607F2CF19CB4E1C996B2563D9B", None),
4     lib\&.Version("3\&.17\&.1", 56787, "3F2FCED08798D83B873B5543BEFA6C4B", None),
5     lib\&.Version("3\&.17\&.2", 56787, "C690FC543082D35EA0AAA876B8362BEA", None),
6     lib\&.Version("3\&.18\&.0", 57507, "1659EF34997DA3470FF84A14431E3A86", None),
7     lib\&.Version("3\&.19\&.0", 58400, "2B06AEE58017A7DF2A3D452D733F1019", None),
8     lib\&.Version("3\&.19\&.1", 58400, "D9B568472880CC4719D1B698C0D86984", None),
9     lib\&.Version("4\&.0\&.0", 59587, "9B4FD995C61664831192B7DA46F8C1A1", None),
10     lib\&.Version("4\&.0\&.2", 59587, "B43D9EE00A363DAFAD46914E3E4AF362", None),
11     lib\&.Version("4\&.1\&.0", 60196, "1B8ACAB0C663D5510941A9871B3E9FBE", None),
12     lib\&.Version("4\&.1\&.1", 60321, "5C021D8A549F4A776EE9E9C1748FFBBC", None),
13     lib\&.Version("4\&.1\&.2", 60321, "33D9FE28909573253B7FC352CE7AEA40", None),
14     lib\&.Version("4\&.2\&.0", 62347, "C0C0E9D37FCDBC437CE386C6BE2D1F93", None),
15     lib\&.Version("4\&.2\&.1", 62848, "29BBAC5AFF364B6101B661DB468E3A37", None),
16     lib\&.Version("4\&.2\&.2", 63454, "3CB54C86777E78557C984AB1CF3494A0", None),
17     lib\&.Version("4\&.3\&.0", 64469, "C92B3E9683D5A59E08FC011F4BE167FF", None),
18     lib\&.Version("4\&.3\&.1", 65094, "E5A21037AA7A25C03AC441515F4E0644", None),
19     lib\&.Version("4\&.3\&.2", 65384, "B6D73C85DFB70F5D01DEABB2517BF11C", None),
20 ]}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
