.TH "pysc2.tests.maps_test.MapsTest" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.maps_test.MapsTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase, and \fBpysc2\&.tests\&.utils\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_list_all_maps\fP (self, map_name)"
.br
.ti -1c
.RI "def \fBtest_load_random_map\fP (self, map_name)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.maps_test\&.MapsTest\&.test_list_all_maps ( self,  map_name)"

.PP
.nf
Make sure all maps can be read.
.fi
.PP
 
.SS "def pysc2\&.tests\&.maps_test\&.MapsTest\&.test_load_random_map ( self,  map_name)"

.PP
.nf
Test loading a few random maps.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
