.TH "pysc2.tests.protocol_error_test.TestProtocolError" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.protocol_error_test.TestProtocolError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.tests\&.utils\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_error\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Verify that we blow up if SC2 thinks we did something wrong.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.protocol_error_test\&.TestProtocolError\&.test_error ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
