.TH "pysc2.tests.random_agent_test.TestRandomAgent" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.random_agent_test.TestRandomAgent
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase, and \fBpysc2\&.tests\&.utils\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_random_agent\fP (self, agent_interface_format)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.random_agent_test\&.TestRandomAgent\&.test_random_agent ( self,  agent_interface_format)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
