.TH "pysc2.env.sc2_env.Race" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.env.sc2_env.Race
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBrandom\fP = sc_common\&.Random"
.br
.ti -1c
.RI "\fBprotoss\fP = sc_common\&.Protoss"
.br
.ti -1c
.RI "\fBterran\fP = sc_common\&.Terran"
.br
.ti -1c
.RI "\fBzerg\fP = sc_common\&.Zerg"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "pysc2\&.env\&.sc2_env\&.Race\&.protoss = sc_common\&.Protoss\fC [static]\fP"

.SS "pysc2\&.env\&.sc2_env\&.Race\&.random = sc_common\&.Random\fC [static]\fP"

.SS "pysc2\&.env\&.sc2_env\&.Race\&.terran = sc_common\&.Terran\fC [static]\fP"

.SS "pysc2\&.env\&.sc2_env\&.Race\&.zerg = sc_common\&.Zerg\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
