.TH "pysc2.bin.agent" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.bin.agent
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBrun_thread\fP (agent_classes, players, map_name, visualize)"
.br
.ti -1c
.RI "def \fBmain\fP (unused_argv)"
.br
.ti -1c
.RI "def \fBentry_point\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFLAGS\fP = flags\&.FLAGS"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.bin\&.agent\&.entry_point ()"

.SS "def pysc2\&.bin\&.agent\&.main ( unused_argv)"

.PP
.nf
Run an agent.
.fi
.PP
 
.SS "def pysc2\&.bin\&.agent\&.run_thread ( agent_classes,  players,  map_name,  visualize)"

.PP
.nf
Run one thread worth of the environment with agents.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.bin\&.agent\&.FLAGS = flags\&.FLAGS"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
