.TH "pysc2.tests.dummy_observation.Builder" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.dummy_observation.Builder
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, obs_spec)"
.br
.ti -1c
.RI "def \fBsingle_select\fP (self, unit)"
.br
.ti -1c
.RI "def \fBmulti_select\fP (self, units)"
.br
.ti -1c
.RI "def \fBfeature_units\fP (self, feature_units)"
.br
.ti -1c
.RI "def \fBbuild\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
For test code - build a dummy ResponseObservation proto.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.tests\&.dummy_observation\&.Builder\&.__init__ ( self,  obs_spec)"

.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.dummy_observation\&.Builder\&.build ( self)"

.PP
.nf
Builds and returns a proto ResponseObservation.
.fi
.PP
 
.SS "def pysc2\&.tests\&.dummy_observation\&.Builder\&.feature_units ( self,  feature_units)"

.SS "def pysc2\&.tests\&.dummy_observation\&.Builder\&.multi_select ( self,  units)"

.SS "def pysc2\&.tests\&.dummy_observation\&.Builder\&.single_select ( self,  unit)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
