.TH "pysc2.bin" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.bin
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBagent\fP"
.br
.ti -1c
.RI " \fBagent_remote\fP"
.br
.ti -1c
.RI " \fBgen_actions\fP"
.br
.ti -1c
.RI " \fBgen_units\fP"
.br
.ti -1c
.RI " \fBgen_versions\fP"
.br
.ti -1c
.RI " \fBmap_list\fP"
.br
.ti -1c
.RI " \fBplay\fP"
.br
.ti -1c
.RI " \fBplay_vs_agent\fP"
.br
.ti -1c
.RI " \fBreplay_actions\fP"
.br
.ti -1c
.RI " \fBreplay_info\fP"
.br
.ti -1c
.RI " \fBrun_tests\fP"
.br
.ti -1c
.RI " \fBvalid_actions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
