.TH "pysc2.lib.named_array_test.BadNamedTuple" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.named_array_test.BadNamedTuple
.SH SYNOPSIS
.br
.PP
.PP
Inherits namedtuple, a, and b\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
