.TH "pysc2.lib.features.ScreenFeatures" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.features.ScreenFeatures
.SH SYNOPSIS
.br
.PP
.PP
Inherits namedtuple, height_map, visibility_map, creep, power, player_id, player_relative, unit_type, selected, unit_hit_points, unit_hit_points_ratio, unit_energy, unit_energy_ratio, unit_shields, unit_shields_ratio, unit_density, unit_density_aa, and effects\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__new__\fP (cls, kwargs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The set of screen feature layers.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.features\&.ScreenFeatures\&.__new__ ( cls,  kwargs)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
