.TH "pysc2.lib.actions.Functions" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.actions.Functions
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, functions)"
.br
.ti -1c
.RI "def \fB__getattr__\fP (self, name)"
.br
.ti -1c
.RI "def \fB__getitem__\fP (self, key)"
.br
.ti -1c
.RI "def \fB__getstate__\fP (self)"
.br
.ti -1c
.RI "def \fB__setstate__\fP (self, functions)"
.br
.ti -1c
.RI "def \fB__iter__\fP (self)"
.br
.ti -1c
.RI "def \fB__len__\fP (self)"
.br
.ti -1c
.RI "def \fB__eq__\fP (self, other)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Represents the full set of functions.

Can't use namedtuple since python3 has a limit of 255 function arguments, so
build something similar.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.lib\&.actions\&.Functions\&.__init__ ( self,  functions)"

.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.actions\&.Functions\&.__eq__ ( self,  other)"

.SS "def pysc2\&.lib\&.actions\&.Functions\&.__getattr__ ( self,  name)"

.SS "def pysc2\&.lib\&.actions\&.Functions\&.__getitem__ ( self,  key)"

.SS "def pysc2\&.lib\&.actions\&.Functions\&.__getstate__ ( self)"

.SS "def pysc2\&.lib\&.actions\&.Functions\&.__iter__ ( self)"

.SS "def pysc2\&.lib\&.actions\&.Functions\&.__len__ ( self)"

.SS "def pysc2\&.lib\&.actions\&.Functions\&.__setstate__ ( self,  functions)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
