.TH "pysc2.bin.gen_units" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.bin.gen_units
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_data\fP ()"
.br
.ti -1c
.RI "def \fBgenerate_py_units\fP (data)"
.br
.ti -1c
.RI "def \fBmain\fP (unused_argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.bin\&.gen_units\&.generate_py_units ( data)"

.PP
.nf
Generate the list of units in units.py.
.fi
.PP
 
.SS "def pysc2\&.bin\&.gen_units\&.get_data ()"

.PP
.nf
Get the game's static data from an actual game.
.fi
.PP
 
.SS "def pysc2\&.bin\&.gen_units\&.main ( unused_argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
