.TH "pysc2.tests.replay_obs_test.GameController" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.replay_obs_test.GameController
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, config)"
.br
.ti -1c
.RI "def \fBstart_replay\fP (self, replay_data)"
.br
.ti -1c
.RI "def \fBcreate_game\fP (self)"
.br
.ti -1c
.RI "def \fBcontroller\fP (self)"
.br
.ti -1c
.RI "def \fBclose\fP (self)"
.br
.ti -1c
.RI "def \fB__enter__\fP (self)"
.br
.ti -1c
.RI "def \fB__exit__\fP (self, exception_type, exception_value, traceback)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Wrapper class for interacting with the game in play/replay mode.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.tests\&.replay_obs_test\&.GameController\&.__init__ ( self,  config)"

.PP
.nf
Constructs the game controller object.

Args:
  config: Interface configuration options.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.replay_obs_test\&.GameController\&.__enter__ ( self)"

.SS "def pysc2\&.tests\&.replay_obs_test\&.GameController\&.__exit__ ( self,  exception_type,  exception_value,  traceback)"

.SS "def pysc2\&.tests\&.replay_obs_test\&.GameController\&.close ( self)"

.PP
.nf
Close the controller connection.
.fi
.PP
 
.SS "def pysc2\&.tests\&.replay_obs_test\&.GameController\&.controller ( self)"

.SS "def pysc2\&.tests\&.replay_obs_test\&.GameController\&.create_game ( self)"

.SS "def pysc2\&.tests\&.replay_obs_test\&.GameController\&.start_replay ( self,  replay_data)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
