.TH "pysc2.lib.renderer_human.MouseButtons" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.renderer_human.MouseButtons
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBLEFT\fP = 1"
.br
.ti -1c
.RI "int \fBMIDDLE\fP = 2"
.br
.ti -1c
.RI "int \fBRIGHT\fP = 3"
.br
.ti -1c
.RI "int \fBWHEEL_UP\fP = 4"
.br
.ti -1c
.RI "int \fBWHEEL_DOWN\fP = 5"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.lib\&.renderer_human\&.MouseButtons\&.LEFT = 1\fC [static]\fP"

.SS "int pysc2\&.lib\&.renderer_human\&.MouseButtons\&.MIDDLE = 2\fC [static]\fP"

.SS "int pysc2\&.lib\&.renderer_human\&.MouseButtons\&.RIGHT = 3\fC [static]\fP"

.SS "int pysc2\&.lib\&.renderer_human\&.MouseButtons\&.WHEEL_DOWN = 5\fC [static]\fP"

.SS "int pysc2\&.lib\&.renderer_human\&.MouseButtons\&.WHEEL_UP = 4\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
