.TH "pysc2.lib.colors.Color" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.colors.Color
.SH SYNOPSIS
.br
.PP
.PP
Inherits namedtuple, r, g, and b\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBset\fP (self, r=None, g=None, b=None)"
.br
.ti -1c
.RI "def \fBround\fP (self)"
.br
.ti -1c
.RI "def \fBfloor\fP (self)"
.br
.ti -1c
.RI "def \fBceil\fP (self)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.ti -1c
.RI "def \fB__add__\fP (self, o)"
.br
.ti -1c
.RI "def \fB__sub__\fP (self, o)"
.br
.ti -1c
.RI "def \fB__mul__\fP (self, val)"
.br
.ti -1c
.RI "def \fB__truediv__\fP (self, val)"
.br
.ti -1c
.RI "def \fB__floordiv__\fP (self, val)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A basic Color class.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.colors\&.Color\&.__add__ ( self,  o)"

.SS "def pysc2\&.lib\&.colors\&.Color\&.__floordiv__ ( self,  val)"

.SS "def pysc2\&.lib\&.colors\&.Color\&.__mul__ ( self,  val)"

.SS "def pysc2\&.lib\&.colors\&.Color\&.__str__ ( self)"

.SS "def pysc2\&.lib\&.colors\&.Color\&.__sub__ ( self,  o)"

.SS "def pysc2\&.lib\&.colors\&.Color\&.__truediv__ ( self,  val)"

.SS "def pysc2\&.lib\&.colors\&.Color\&.ceil ( self)"

.SS "def pysc2\&.lib\&.colors\&.Color\&.floor ( self)"

.SS "def pysc2\&.lib\&.colors\&.Color\&.round ( self)"

.SS "def pysc2\&.lib\&.colors\&.Color\&.set ( self,  r = \fCNone\fP,  g = \fCNone\fP,  b = \fCNone\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
