.TH "pysc2.lib.stopwatch.FakeStopWatchContext" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.stopwatch.FakeStopWatchContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__enter__\fP (self)"
.br
.ti -1c
.RI "def \fB__exit__\fP (self, unused_exception_type, unused_exc_value, unused_traceback)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A fake stopwatch context for when the stopwatch is too slow or unneeded.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.stopwatch\&.FakeStopWatchContext\&.__enter__ ( self)"

.SS "def pysc2\&.lib\&.stopwatch\&.FakeStopWatchContext\&.__exit__ ( self,  unused_exception_type,  unused_exc_value,  unused_traceback)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
