.TH "pysc2.bin.play" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.bin.play
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP (unused_argv)"
.br
.ti -1c
.RI "def \fBget_replay_version\fP (replay_data)"
.br
.ti -1c
.RI "def \fBentry_point\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFLAGS\fP = flags\&.FLAGS"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.bin\&.play\&.entry_point ()"

.SS "def pysc2\&.bin\&.play\&.get_replay_version ( replay_data)"

.SS "def pysc2\&.bin\&.play\&.main ( unused_argv)"

.PP
.nf
Run SC2 to play a game or a replay.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.bin\&.play\&.FLAGS = flags\&.FLAGS"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
