.TH "pysc2.lib.stopwatch_test.StopwatchTest" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.stopwatch_test.StopwatchTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtestStopwatch\fP (self, mock_time)"
.br
.ti -1c
.RI "def \fBtestDivideZero\fP (self)"
.br
.ti -1c
.RI "def \fBtestSpeed\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.stopwatch_test\&.StopwatchTest\&.testDivideZero ( self)"

.SS "def pysc2\&.lib\&.stopwatch_test\&.StopwatchTest\&.testSpeed ( self)"

.SS "def pysc2\&.lib\&.stopwatch_test\&.StopwatchTest\&.testStopwatch ( self,  mock_time)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
