.TH "pysc2.tests.easy_scripted_test.TestEasy" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.easy_scripted_test.TestEasy
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.tests\&.utils\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_move_to_beacon\fP (self)"
.br
.ti -1c
.RI "def \fBtest_collect_mineral_shards\fP (self)"
.br
.ti -1c
.RI "def \fBtest_collect_mineral_shards_feature_units\fP (self)"
.br
.ti -1c
.RI "def \fBtest_defeat_roaches\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsteps\fP = 200"
.br
.ti -1c
.RI "int \fBstep_mul\fP = 16"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.easy_scripted_test\&.TestEasy\&.test_collect_mineral_shards ( self)"

.SS "def pysc2\&.tests\&.easy_scripted_test\&.TestEasy\&.test_collect_mineral_shards_feature_units ( self)"

.SS "def pysc2\&.tests\&.easy_scripted_test\&.TestEasy\&.test_defeat_roaches ( self)"

.SS "def pysc2\&.tests\&.easy_scripted_test\&.TestEasy\&.test_move_to_beacon ( self)"

.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.tests\&.easy_scripted_test\&.TestEasy\&.step_mul = 16\fC [static]\fP"

.SS "int pysc2\&.tests\&.easy_scripted_test\&.TestEasy\&.steps = 200\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
