.TH "pysc2.lib.transform.Linear" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.transform.Linear
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.lib\&.transform\&.Transform\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBscale\fP=None, \fBoffset\fP=None)"
.br
.ti -1c
.RI "def \fBfwd_dist\fP (self, dist)"
.br
.ti -1c
.RI "def \fBfwd_pt\fP (self, pt)"
.br
.ti -1c
.RI "def \fBback_dist\fP (self, dist)"
.br
.ti -1c
.RI "def \fBback_pt\fP (self, pt)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBscale\fP"
.br
.ti -1c
.RI "\fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A linear transform with a scale and offset.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.lib\&.transform\&.Linear\&.__init__ ( self,  scale = \fCNone\fP,  offset = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.transform\&.Linear\&.__str__ ( self)"

.SS "def pysc2\&.lib\&.transform\&.Linear\&.back_dist ( self,  dist)"

.SS "def pysc2\&.lib\&.transform\&.Linear\&.back_pt ( self,  pt)"

.SS "def pysc2\&.lib\&.transform\&.Linear\&.fwd_dist ( self,  dist)"

.SS "def pysc2\&.lib\&.transform\&.Linear\&.fwd_pt ( self,  pt)"

.SH "Member Data Documentation"
.PP 
.SS "pysc2\&.lib\&.transform\&.Linear\&.offset"

.SS "pysc2\&.lib\&.transform\&.Linear\&.scale"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
