.TH "pysc2.env.sc2_env.Difficulty" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.env.sc2_env.Difficulty
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBvery_easy\fP = sc_pb\&.VeryEasy"
.br
.ti -1c
.RI "\fBeasy\fP = sc_pb\&.Easy"
.br
.ti -1c
.RI "\fBmedium\fP = sc_pb\&.Medium"
.br
.ti -1c
.RI "\fBmedium_hard\fP = sc_pb\&.MediumHard"
.br
.ti -1c
.RI "\fBhard\fP = sc_pb\&.Hard"
.br
.ti -1c
.RI "\fBharder\fP = sc_pb\&.Harder"
.br
.ti -1c
.RI "\fBvery_hard\fP = sc_pb\&.VeryHard"
.br
.ti -1c
.RI "\fBcheat_vision\fP = sc_pb\&.CheatVision"
.br
.ti -1c
.RI "\fBcheat_money\fP = sc_pb\&.CheatMoney"
.br
.ti -1c
.RI "\fBcheat_insane\fP = sc_pb\&.CheatInsane"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Bot difficulties.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pysc2\&.env\&.sc2_env\&.Difficulty\&.cheat_insane = sc_pb\&.CheatInsane\fC [static]\fP"

.SS "pysc2\&.env\&.sc2_env\&.Difficulty\&.cheat_money = sc_pb\&.CheatMoney\fC [static]\fP"

.SS "pysc2\&.env\&.sc2_env\&.Difficulty\&.cheat_vision = sc_pb\&.CheatVision\fC [static]\fP"

.SS "pysc2\&.env\&.sc2_env\&.Difficulty\&.easy = sc_pb\&.Easy\fC [static]\fP"

.SS "pysc2\&.env\&.sc2_env\&.Difficulty\&.hard = sc_pb\&.Hard\fC [static]\fP"

.SS "pysc2\&.env\&.sc2_env\&.Difficulty\&.harder = sc_pb\&.Harder\fC [static]\fP"

.SS "pysc2\&.env\&.sc2_env\&.Difficulty\&.medium = sc_pb\&.Medium\fC [static]\fP"

.SS "pysc2\&.env\&.sc2_env\&.Difficulty\&.medium_hard = sc_pb\&.MediumHard\fC [static]\fP"

.SS "pysc2\&.env\&.sc2_env\&.Difficulty\&.very_easy = sc_pb\&.VeryEasy\fC [static]\fP"

.SS "pysc2\&.env\&.sc2_env\&.Difficulty\&.very_hard = sc_pb\&.VeryHard\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
