.TH "pysc2.env.environment.StepType" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.env.environment.StepType
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBFIRST\fP = 0"
.br
.ti -1c
.RI "int \fBMID\fP = 1"
.br
.ti -1c
.RI "int \fBLAST\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Defines the status of a `TimeStep` within a sequence.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.env\&.environment\&.StepType\&.FIRST = 0\fC [static]\fP"

.SS "int pysc2\&.env\&.environment\&.StepType\&.LAST = 2\fC [static]\fP"

.SS "int pysc2\&.env\&.environment\&.StepType\&.MID = 1\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
