.TH "pysc2.tests.versions_test.TestVersions" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.versions_test.TestVersions
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_version_numbers\fP (self, game_version, version)"
.br
.ti -1c
.RI "def \fBtest_versions_create_game\fP (self, game_version)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.versions_test\&.TestVersions\&.test_version_numbers ( self,  game_version,  version)"

.SS "def pysc2\&.tests\&.versions_test\&.TestVersions\&.test_versions_create_game ( self,  game_version)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
