.TH "pysc2.lib.renderer_human.MousePos" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.renderer_human.MousePos
.SH SYNOPSIS
.br
.PP
.PP
Inherits namedtuple, world_pos, and surf\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsurf_pos\fP (self)"
.br
.ti -1c
.RI "def \fBobs_pos\fP (self)"
.br
.ti -1c
.RI "def \fBaction_spatial\fP (self, action)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Holds the mouse position in world coordinates and the surf it came from.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.renderer_human\&.MousePos\&.action_spatial ( self,  action)"

.PP
.nf
Given an Action, return the right spatial action.
.fi
.PP
 
.SS "def pysc2\&.lib\&.renderer_human\&.MousePos\&.obs_pos ( self)"

.SS "def pysc2\&.lib\&.renderer_human\&.MousePos\&.surf_pos ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
