.TH "pysc2.maps.mini_games.MiniGame" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.maps.mini_games.MiniGame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.maps\&.lib\&.Map\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBdirectory\fP = 'mini_games'"
.br
.ti -1c
.RI "string \fBdownload\fP = 'https://github\&.com/deepmind/pysc2#\fBget\fP\-the\-maps'"
.br
.ti -1c
.RI "int \fBplayers\fP = 1"
.br
.ti -1c
.RI "int \fBscore_index\fP = 0"
.br
.ti -1c
.RI "int \fBgame_steps_per_episode\fP = 0"
.br
.ti -1c
.RI "int \fBstep_mul\fP = 8"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Data Documentation"
.PP 
.SS "string pysc2\&.maps\&.mini_games\&.MiniGame\&.directory = 'mini_games'\fC [static]\fP"

.SS "string pysc2\&.maps\&.mini_games\&.MiniGame\&.download = 'https://github\&.com/deepmind/pysc2#\fBget\fP\-the\-maps'\fC [static]\fP"

.SS "int pysc2\&.maps\&.mini_games\&.MiniGame\&.game_steps_per_episode = 0\fC [static]\fP"

.SS "int pysc2\&.maps\&.mini_games\&.MiniGame\&.players = 1\fC [static]\fP"

.SS "int pysc2\&.maps\&.mini_games\&.MiniGame\&.score_index = 0\fC [static]\fP"

.SS "int pysc2\&.maps\&.mini_games\&.MiniGame\&.step_mul = 8\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
