.TH "pysc2.tests.utils.TestCase" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.utils.TestCase
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.PP
Inherited by \fBpysc2\&.tests\&.easy_scripted_test\&.TestEasy\fP, \fBpysc2\&.tests\&.maps_test\&.MapsTest\fP, \fBpysc2\&.tests\&.multi_player_env_test\&.TestMultiplayerEnv\fP, \fBpysc2\&.tests\&.multi_player_test\&.TestMultiplayer\fP, \fBpysc2\&.tests\&.obs_spec_test\&.TestObservationSpec\fP, \fBpysc2\&.tests\&.observer_test\&.TestObserver\fP, \fBpysc2\&.tests\&.ping_test\&.TestPing\fP, \fBpysc2\&.tests\&.protocol_error_test\&.TestProtocolError\fP, \fBpysc2\&.tests\&.random_agent_test\&.TestRandomAgent\fP, \fBpysc2\&.tests\&.render_test\&.TestRender\fP, and \fBpysc2\&.tests\&.replay_obs_test\&.ReplayObsTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtearDown\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A test base class that enables stopwatch profiling.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.utils\&.TestCase\&.setUp ( self)"

.SS "def pysc2\&.tests\&.utils\&.TestCase\&.tearDown ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
