.TH "pysc2.run_configs.platforms.Linux" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.run_configs.platforms.Linux
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.run_configs\&.platforms\&.LocalBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBpriority\fP (cls)"
.br
.ti -1c
.RI "def \fBstart\fP (self, kwargs)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBknown_mesa\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
Config to run on Linux.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.run_configs\&.platforms\&.Linux\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.run_configs\&.platforms\&.Linux\&.priority ( cls)"

.SS "def pysc2\&.run_configs\&.platforms\&.Linux\&.start ( self,  kwargs)"

.SH "Member Data Documentation"
.PP 
.SS "list pysc2\&.run_configs\&.platforms\&.Linux\&.known_mesa\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=  [  # In priority order
      "libOSMesa\&.so",
      "libOSMesa\&.so\&.8",  # Ubuntu 16\&.04
      "libOSMesa\&.so\&.6",  # Ubuntu 14\&.04
  ]
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
