.TH "pysc2.lib.features.MinimapFeatures" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.features.MinimapFeatures
.SH SYNOPSIS
.br
.PP
.PP
Inherits namedtuple, height_map, visibility_map, creep, camera, player_id, player_relative, and selected\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__new__\fP (cls, kwargs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The set of minimap feature layers.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.features\&.MinimapFeatures\&.__new__ ( cls,  kwargs)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
