.TH "pysc2.bin.valid_actions" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.bin.valid_actions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP (unused_argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFLAGS\fP = flags\&.FLAGS"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.bin\&.valid_actions\&.main ( unused_argv)"

.PP
.nf
Print the valid actions.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.bin\&.valid_actions\&.FLAGS = flags\&.FLAGS"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
