.TH "pysc2.run_configs" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.run_configs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlib\fP"
.br
.ti -1c
.RI " \fBplatforms\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFLAGS\fP = flags\&.FLAGS"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.run_configs\&.get ()"

.PP
.nf
Get the config chosen by the flags.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pysc2\&.run_configs\&.FLAGS = flags\&.FLAGS"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
