.TH "pysc2.env.mock_sc2_env_comparison_test.TestCompareEnvironments" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.env.mock_sc2_env_comparison_test.TestCompareEnvironments
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUpClass\fP (cls)"
.br
.ti -1c
.RI "def \fBtearDownClass\fP (cls)"
.br
.ti -1c
.RI "def \fBtest_observation_spec\fP (self)"
.br
.ti -1c
.RI "def \fBtest_action_spec\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.env\&.mock_sc2_env_comparison_test\&.TestCompareEnvironments\&.setUpClass ( cls)"

.SS "def pysc2\&.env\&.mock_sc2_env_comparison_test\&.TestCompareEnvironments\&.tearDownClass ( cls)"

.SS "def pysc2\&.env\&.mock_sc2_env_comparison_test\&.TestCompareEnvironments\&.test_action_spec ( self)"

.SS "def pysc2\&.env\&.mock_sc2_env_comparison_test\&.TestCompareEnvironments\&.test_observation_spec ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
