.TH "pysc2.env.mock_sc2_env_test.TestTestEnvironment" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.env.mock_sc2_env_test.TestTestEnvironment
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.env\&.mock_sc2_env_test\&._TestMixin\fP, and TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtest_observation_spec\fP (self)"
.br
.ti -1c
.RI "def \fBtest_action_spec\fP (self)"
.br
.ti -1c
.RI "def \fBtest_default_observation\fP (self)"
.br
.ti -1c
.RI "def \fBtest_episode\fP (self)"
.br
.ti -1c
.RI "def \fBtest_two_episodes\fP (self)"
.br
.ti -1c
.RI "def \fBtest_episode_length\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.env\&.mock_sc2_env_test\&.TestTestEnvironment\&.setUp ( self)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&.TestTestEnvironment\&.test_action_spec ( self)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&.TestTestEnvironment\&.test_default_observation ( self)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&.TestTestEnvironment\&.test_episode ( self)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&.TestTestEnvironment\&.test_episode_length ( self)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&.TestTestEnvironment\&.test_observation_spec ( self)"

.SS "def pysc2\&.env\&.mock_sc2_env_test\&.TestTestEnvironment\&.test_two_episodes ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
