.TH "pysc2.tests.maps_test" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.maps_test
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMapsTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_maps\fP (count=None)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.maps_test\&.get_maps ( count = \fCNone\fP)"

.PP
.nf
Test only a few random maps to minimize time.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
