.TH "pysc2.lib.point_flag" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.point_flag
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPointParser\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBDEFINE_point\fP (name, default, help)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.point_flag\&.DEFINE_point ( name,  default,  help)"

.PP
.nf
Registers a flag whose value parses as a point.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
