.TH "pysc2.lib.static_data.StaticData" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.static_data.StaticData
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, data)"
.br
.ti -1c
.RI "def \fBabilities\fP (self)"
.br
.ti -1c
.RI "def \fBunits\fP (self)"
.br
.ti -1c
.RI "def \fBgeneral_abilities\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Expose static data in a more useful form than the raw protos.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.lib\&.static_data\&.StaticData\&.__init__ ( self,  data)"

.PP
.nf
Takes data from RequestData.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.static_data\&.StaticData\&.abilities ( self)"

.SS "def pysc2\&.lib\&.static_data\&.StaticData\&.general_abilities ( self)"

.SS "def pysc2\&.lib\&.static_data\&.StaticData\&.units ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
