.TH "pysc2.lib.named_array_test.TestEnum" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.named_array_test.TestEnum
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBa\fP = 0"
.br
.ti -1c
.RI "int \fBb\fP = 1"
.br
.ti -1c
.RI "int \fBc\fP = 2"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.lib\&.named_array_test\&.TestEnum\&.a = 0\fC [static]\fP"

.SS "int pysc2\&.lib\&.named_array_test\&.TestEnum\&.b = 1\fC [static]\fP"

.SS "int pysc2\&.lib\&.named_array_test\&.TestEnum\&.c = 2\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
