.TH "pysc2.lib.features_test.DimensionsTest" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.features_test.DimensionsTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtestScreenSizeWithoutMinimapRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestScreenWidthWithoutHeightRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestScreenWidthHeightWithoutMinimapRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestMinimapWidthAndHeightWithoutScreenRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestScreenSmallerThanMinimapRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestNoneNoneRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestSingularZeroesRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestTwoZeroesRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestThreeTupleScreenRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestThreeTupleMinimapRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestNegativeScreenRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestNegativeMinimapRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestNegativeScreenTupleRaises\fP (self)"
.br
.ti -1c
.RI "def \fBtestNegativeMinimapTupleRaises\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testMinimapWidthAndHeightWithoutScreenRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testNegativeMinimapRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testNegativeMinimapTupleRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testNegativeScreenRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testNegativeScreenTupleRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testNoneNoneRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testScreenSizeWithoutMinimapRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testScreenSmallerThanMinimapRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testScreenWidthHeightWithoutMinimapRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testScreenWidthWithoutHeightRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testSingularZeroesRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testThreeTupleMinimapRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testThreeTupleScreenRaises ( self)"

.SS "def pysc2\&.lib\&.features_test\&.DimensionsTest\&.testTwoZeroesRaises ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
