.TH "pysc2.tests.obs_spec_test.TestObservationSpec" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.tests.obs_spec_test.TestObservationSpec
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.tests\&.utils\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_observation_matches_obs_spec\fP (self)"
.br
.ti -1c
.RI "def \fBtest_heterogeneous_observations\fP (self)"
.br
.ti -1c
.RI "def \fBcheck_observation_matches_spec\fP (self, obs, obs_spec)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.tests\&.obs_spec_test\&.TestObservationSpec\&.check_observation_matches_spec ( self,  obs,  obs_spec)"

.SS "def pysc2\&.tests\&.obs_spec_test\&.TestObservationSpec\&.test_heterogeneous_observations ( self)"

.SS "def pysc2\&.tests\&.obs_spec_test\&.TestObservationSpec\&.test_observation_matches_obs_spec ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
