.TH "pysc2.bin.replay_info" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.bin.replay_info
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP (argv)"
.br
.ti -1c
.RI "def \fBentry_point\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.bin\&.replay_info\&.entry_point ()"

.SS "def pysc2\&.bin\&.replay_info\&.main ( argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
