.TH "pysc2.env.run_loop" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.env.run_loop
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBrun_loop\fP (agents, env, max_frames=0, max_episodes=0)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pysc2\&.env\&.run_loop\&.run_loop ( agents,  env,  max_frames = \fC0\fP,  max_episodes = \fC0\fP)"

.PP
.nf
A run loop to have agents and an environment interact.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
