.TH "pysc2.run_configs.platforms.MacOS" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.run_configs.platforms.MacOS
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysc2\&.run_configs\&.platforms\&.LocalBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBpriority\fP (cls)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
Run on MacOS.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pysc2\&.run_configs\&.platforms\&.MacOS\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "def pysc2\&.run_configs\&.platforms\&.MacOS\&.priority ( cls)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
