.TH "pysc2.lib.units.Protoss" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysc2.lib.units.Protoss
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBAdept\fP = 311"
.br
.ti -1c
.RI "int \fBAdeptPhaseShift\fP = 801"
.br
.ti -1c
.RI "int \fBArchon\fP = 141"
.br
.ti -1c
.RI "int \fBAssimilator\fP = 61"
.br
.ti -1c
.RI "int \fBCarrier\fP = 79"
.br
.ti -1c
.RI "int \fBColossus\fP = 4"
.br
.ti -1c
.RI "int \fBCyberneticsCore\fP = 72"
.br
.ti -1c
.RI "int \fBDarkShrine\fP = 69"
.br
.ti -1c
.RI "int \fBDarkTemplar\fP = 76"
.br
.ti -1c
.RI "int \fBDisruptor\fP = 694"
.br
.ti -1c
.RI "int \fBDisruptorPhased\fP = 733"
.br
.ti -1c
.RI "int \fBFleetBeacon\fP = 64"
.br
.ti -1c
.RI "int \fBForceField\fP = 135"
.br
.ti -1c
.RI "int \fBForge\fP = 63"
.br
.ti -1c
.RI "int \fBGateway\fP = 62"
.br
.ti -1c
.RI "int \fBHighTemplar\fP = 75"
.br
.ti -1c
.RI "int \fBImmortal\fP = 83"
.br
.ti -1c
.RI "int \fBInterceptor\fP = 85"
.br
.ti -1c
.RI "int \fBMothership\fP = 10"
.br
.ti -1c
.RI "int \fBMothershipCore\fP = 488"
.br
.ti -1c
.RI "int \fBNexus\fP = 59"
.br
.ti -1c
.RI "int \fBObserver\fP = 82"
.br
.ti -1c
.RI "int \fBObserverSurveillanceMode\fP = 1911"
.br
.ti -1c
.RI "int \fBOracle\fP = 495"
.br
.ti -1c
.RI "int \fBPhoenix\fP = 78"
.br
.ti -1c
.RI "int \fBPhotonCannon\fP = 66"
.br
.ti -1c
.RI "int \fBProbe\fP = 84"
.br
.ti -1c
.RI "int \fBPylon\fP = 60"
.br
.ti -1c
.RI "int \fBPylonOvercharged\fP = 894"
.br
.ti -1c
.RI "int \fBRoboticsBay\fP = 70"
.br
.ti -1c
.RI "int \fBRoboticsFacility\fP = 71"
.br
.ti -1c
.RI "int \fBSentry\fP = 77"
.br
.ti -1c
.RI "int \fBShieldBattery\fP = 1910"
.br
.ti -1c
.RI "int \fBStalker\fP = 74"
.br
.ti -1c
.RI "int \fBStargate\fP = 67"
.br
.ti -1c
.RI "int \fBStasisTrap\fP = 732"
.br
.ti -1c
.RI "int \fBTempest\fP = 496"
.br
.ti -1c
.RI "int \fBTemplarArchive\fP = 68"
.br
.ti -1c
.RI "int \fBTwilightCouncil\fP = 65"
.br
.ti -1c
.RI "int \fBVoidRay\fP = 80"
.br
.ti -1c
.RI "int \fBWarpGate\fP = 133"
.br
.ti -1c
.RI "int \fBWarpPrism\fP = 81"
.br
.ti -1c
.RI "int \fBWarpPrismPhasing\fP = 136"
.br
.ti -1c
.RI "int \fBZealot\fP = 73"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Protoss units.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int pysc2\&.lib\&.units\&.Protoss\&.Adept = 311\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.AdeptPhaseShift = 801\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Archon = 141\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Assimilator = 61\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Carrier = 79\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Colossus = 4\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.CyberneticsCore = 72\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.DarkShrine = 69\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.DarkTemplar = 76\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Disruptor = 694\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.DisruptorPhased = 733\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.FleetBeacon = 64\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.ForceField = 135\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Forge = 63\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Gateway = 62\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.HighTemplar = 75\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Immortal = 83\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Interceptor = 85\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Mothership = 10\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.MothershipCore = 488\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Nexus = 59\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Observer = 82\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.ObserverSurveillanceMode = 1911\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Oracle = 495\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Phoenix = 78\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.PhotonCannon = 66\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Probe = 84\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Pylon = 60\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.PylonOvercharged = 894\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.RoboticsBay = 70\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.RoboticsFacility = 71\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Sentry = 77\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.ShieldBattery = 1910\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Stalker = 74\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Stargate = 67\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.StasisTrap = 732\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Tempest = 496\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.TemplarArchive = 68\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.TwilightCouncil = 65\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.VoidRay = 80\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.WarpGate = 133\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.WarpPrism = 81\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.WarpPrismPhasing = 136\fC [static]\fP"

.SS "int pysc2\&.lib\&.units\&.Protoss\&.Zealot = 73\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
