.TH "env/remote_sc2_env.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
env/remote_sc2_env.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.env\&.remote_sc2_env\&.RestartException\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.env\&.remote_sc2_env\&.RemoteSC2Env\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.env\&.remote_sc2_env\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
