.TH "lib/renderer_human.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/renderer_human.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.lib\&.renderer_human\&.MouseButtons\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.renderer_human\&.SurfType\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.renderer_human\&.ActionCmd\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.renderer_human\&._Surface\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.renderer_human\&.MousePos\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.renderer_human\&.PastAction\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.renderer_human\&.RendererHuman\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.lib\&.renderer_human\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpysc2\&.lib\&.renderer_human\&.with_lock\fP (lock)"
.br
.ti -1c
.RI "def \fBpysc2\&.lib\&.renderer_human\&.clamp\fP (n, smallest, largest)"
.br
.ti -1c
.RI "def \fBpysc2\&.lib\&.renderer_human\&.circle_mask\fP (shape, pt, radius)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpysc2\&.lib\&.renderer_human\&.sw\fP = stopwatch\&.sw"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.renderer_human\&.render_lock\fP = threading\&.Lock()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
