.TH "tests/replay_obs_test.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/replay_obs_test.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.tests\&.replay_obs_test\&.Config\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.tests\&.replay_obs_test\&.GameController\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.tests\&.replay_obs_test\&.ReplayObsTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.tests\&.replay_obs_test\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpysc2\&.tests\&.replay_obs_test\&.identity_function\fP (name, args)"
.br
.ti -1c
.RI "def \fBpysc2\&.tests\&.replay_obs_test\&.any_point\fP (unit_type, obs)"
.br
.ti -1c
.RI "def \fBpysc2\&.tests\&.replay_obs_test\&.avg_point\fP (unit_type, obs)"
.br
.ti -1c
.RI "def \fBpysc2\&.tests\&.replay_obs_test\&.select\fP (func, unit_type)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dictionary \fBpysc2\&.tests\&.replay_obs_test\&.printable_unit_types\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
