.TH "env/sc2_env.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
env/sc2_env.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.env\&.sc2_env\&.Race\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.env\&.sc2_env\&.Difficulty\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.env\&.sc2_env\&.SC2Env\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.env\&.sc2_env\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpysc2\&.env\&.sc2_env\&.sw\fP = stopwatch\&.sw"
.br
.ti -1c
.RI "dictionary \fBpysc2\&.env\&.sc2_env\&.possible_results\fP"
.br
.ti -1c
.RI "\fBpysc2\&.env\&.sc2_env\&.ActionSpace\fP = actions_lib\&.ActionSpace"
.br
.ti -1c
.RI "\fBpysc2\&.env\&.sc2_env\&.Dimensions\fP = features\&.Dimensions"
.br
.ti -1c
.RI "\fBpysc2\&.env\&.sc2_env\&.AgentInterfaceFormat\fP = features\&.AgentInterfaceFormat"
.br
.ti -1c
.RI "\fBpysc2\&.env\&.sc2_env\&.parse_agent_interface_format\fP = features\&.parse_agent_interface_format"
.br
.ti -1c
.RI "\fBpysc2\&.env\&.sc2_env\&.Agent\fP = collections\&.namedtuple('Agent', ['race'])"
.br
.ti -1c
.RI "\fBpysc2\&.env\&.sc2_env\&.Bot\fP = collections\&.namedtuple('Bot', ['race', 'difficulty'])"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
