.TH "agents/scripted_agent.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
agents/scripted_agent.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.agents\&.scripted_agent\&.MoveToBeacon\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.agents\&.scripted_agent\&.CollectMineralShards\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.agents\&.scripted_agent\&.CollectMineralShardsFeatureUnits\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.agents\&.scripted_agent\&.DefeatRoaches\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.agents\&.scripted_agent\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpysc2\&.agents\&.scripted_agent\&.FUNCTIONS\fP = actions\&.FUNCTIONS"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
