.TH "lib/stopwatch.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/stopwatch.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.lib\&.stopwatch\&.Stat\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.stopwatch\&.StopWatchContext\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.stopwatch\&.TracingStopWatchContext\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.stopwatch\&.FakeStopWatchContext\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.stopwatch\&.StopWatch\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.lib\&.stopwatch\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpysc2\&.lib\&.stopwatch\&.fake_context\fP = FakeStopWatchContext()"
.br
.ti -1c
.RI "\fBpysc2\&.lib\&.stopwatch\&.sw\fP = StopWatch(enabled=False)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
