.TH "lib/transform.py" 3 "Fri Sep 28 2018" "UIUCscaipy2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/transform.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysc2\&.lib\&.transform\&.Transform\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.transform\&.Linear\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.transform\&.Chain\fP"
.br
.ti -1c
.RI "class \fBpysc2\&.lib\&.transform\&.PixelToCoord\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysc2\&.lib\&.transform\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UIUCscaipy2 from the source code\&.
